### ISSUE TITLE
Arguments not being passed to vararg methods correctly

### ISSUE THREAD

**Issue by tpoliaw** [jython/jython#100]
If a Java method such as

    public static void foo(Object... args) {}

is called from Jython as

    foo(1, 2, [3,4])

The call should be valid and the `args`that gets passed to the Java method should be `[1, 2, [3, 4]]`.

The current method checks the final arg to check if it's a sequence and assumes the varargs are already being passed as a list so the call fails. A similar call without the list (eg `foo(1, 2, 3)`) works as expected.

A similar bug (but the other way around) can be see by calling a Java method such as

    static void foo(int[] a, int... b) {}

as 

    foo([1,2,3])

which should be valid, but needs an additional empty list added to fit the vararg signature.

**Comment by tpoliaw** [comment]
I think this is fixed by #101. Thanks for reviewing it.

**Comment by jeff5** [comment]
> I think this is fixed by #101. Thanks for reviewing it.

Right, I should've mentioned this one in the consolidate commit message, so it would get closed. Thanks to you for solving it.
