### ISSUE TITLE
Jython is not working on GraalVM's Native Image

### ISSUE THREAD

**Issue by jovanstevanovic** [jython/jython#108]
On the Native Image (NI) side, we are using Native Image Agent (NIA) to collect all classes that are generated dynamically. One of those classes is `encodings$py` generated from here: https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/Lib/encodings/__init__.py. NIA will create a unique hash out of class bytecode as an entry for internal hashmap. After NIA, we are starting NI builder as a separate process to build executable out of bytecode. 

The problem is that the bytecode for `encodings$py` will be different between NIA and NI builder. The reason is that this class is taking compile-time information (current time, constant in a pool) and information about the path to the __init__.py file (also constant, with a different value between executions in our case). For more details, see diff: https://www.diffchecker.com/e4pfN6rp.

Is there a solid reason to use these constants? Can we avoid this problem somehow? 

Kind regards!

**Comment by jeff5** [comment]
Without understanding the Graal context you describe, I can still explain the constants. These are annotations  written here: https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/compiler/ClassFile.java#L249-L258 .

The time is used to decide whether a file is stale (needs recompiling) during import. It's the last-modified time on the source. It is used here (and the file name is used on the last line): https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/core/imp.java#L400-L415

Looking at your diff, I don't see much value in capturing the full path, and then the file name would be the same. Note that the time is a property of the source, not of the time of compilation.
