### ISSUE TITLE
ctypes.CDLL("libgcc_s.so.1") causes java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#111]
CPython can work well on the following example, however it crashes Jython with java.lang.UnsatisfiedLinkError

test.py
```
import ctypes
libgcc_s = ctypes.CDLL("libgcc_s.so.1")

```

crash report:

> (base) xxm@xxm-System-Product-Name:~/Desktop/IFuzzer/bugs/Jython$ jython test.py 
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File "test.py", line 2, in <module>
>     libgcc_s = ctypes.CDLL("libgcc_s.so.1")
>   File "/usr/share/jython/Lib/ctypes/__init__.py", line 262, in __init__
>     self._handle = jffi.dlopen(name, mode)
> 	at com.kenai.jffi.Foreign.newLoadError(Foreign.java:72)
> 	at com.kenai.jffi.Foreign.access$300(Foreign.java:42)
> 	at com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:98)
> 	at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
> 	at com.kenai.jffi.Library.openLibrary(Library.java:151)
> 	at com.kenai.jffi.Library.getCachedInstance(Library.java:125)
> 	at org.python.modules.jffi.DynamicLibrary.<init>(DynamicLibrary.java:24)
> 	at org.python.modules.jffi.jffi.dlopen(jffi.java:44)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 
> java.lang.UnsatisfiedLinkError: java.lang.UnsatisfiedLinkError
> 

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292

**Comment by Stewori** [comment]
In addition to [this comment](https://github.com/jython/jython/issues/109#issuecomment-890923964), note that Jython lacks C-extension support and the ctypes module is well known to be very incomplete. You can use [JyNI](https://github.com/Stewori/JyNI) for some C-extensions, including ctypes.

**Comment by xiaxinmeng** [comment]
I see. Thank you for your explanation!
