### ISSUE TITLE
ctypes causes IllegalStateException of Jython

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#113]
See the following programs, we define a structure class and set c_int pr c_uint32 to _fields_. The Jython crashes with the following IllegalStateException.

test1.py
```

from ctypes import *

class S(Structure):
        _fields_ = [('x', c_int)]

test2.py
import ctypes
class Struct(ctypes.Structure):
    _fields_ = [('a', ctypes.c_uint32)] 

```

Crash Reported:

> xxm@xxm-System-Product-Name:~$ jython test.py
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
> Traceback (most recent call last):
>   File test.py, line 3, in <module>
>     class S(Structure):
>   File "/usr/share/jython/Lib/ctypes/__init__.py", line 127, in __new__
>     return _AggregateMetaClass.__new_aggregate__(cls, name, bases, dict, union = False)
>   File "/usr/share/jython/Lib/ctypes/__init__.py", line 95, in __new_aggregate__
>     layout = dict['_jffi_type'] = _StructLayoutBuilder(union).add_fields(dict['_fields_']).build()
>   File "/usr/share/jython/Lib/ctypes/__init__.py", line 70, in add_fields
>     self.add_field(f)
>   File "/usr/share/jython/Lib/ctypes/__init__.py", line 80, in add_field
>     self.offset = self.align(self.offset, alignment(f[1]))
>   File "/usr/share/jython/Lib/ctypes/__init__.py", line 146, in alignment
>     return type._jffi_type.alignment()
> java.lang.IllegalStateException: Can't overwrite cause with java.lang.UnsatisfiedLinkError
>     at java.lang.Throwable.initCause(Throwable.java:458)
>     at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:252)
>     at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
>     at com.kenai.jffi.Type.resolveAlignment(Type.java:159)
>     at com.kenai.jffi.Type.alignment(Type.java:147)
>     at org.python.modules.jffi.CType.alignment(CType.java:61)
>     at org.python.modules.jffi.CType.pyalignment(CType.java:75)
>     .......
>     at org.python.core.io.TextIOBase.isatty(TextIOBase.java:175)
>     at org.python.core.PyFile.file_isatty(PyFile.java:485)
>     at org.python.core.PyFile.isatty(PyFile.java:480)
>     at org.python.core.PySystemState.initEncoding(PySystemState.java:247)
>     at org.python.core.PySystemState.<init>(PySystemState.java:191)
>     at org.python.core.PySystemState.doInitialize(PySystemState.java:892)
>     at org.python.core.PySystemState.initialize(PySystemState.java:802)
>     at org.python.core.PySystemState.initialize(PySystemState.java:752)
>     at org.python.core.PySystemState.initialize(PySystemState.java:745)
>     at org.python.util.jython.run(jython.java:150)
>     ... 1 more
> 
> java.lang.IllegalStateException: java.lang.IllegalStateException: Can't overwrite cause with java.lang.UnsatisfiedLinkError
> 
> 

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292

**Comment by Stewori** [comment]
See [this comment](https://github.com/jython/jython/issues/111#issuecomment-890926544).

**Comment by xiaxinmeng** [comment]
Thank you!

**Comment by jeff5** [comment]
Unsupported version.
