### ISSUE TITLE
Inconsistent behavior of nonlocal between CPython and Jython

### ISSUE THREAD

**Issue by xiaxinmeng** [jython/jython#117]
The behavior of nonlocal keyword in Jython is inconsistent with CPython. SyntaxError is returned. The following example should report no error.

test.py
```
def test_proxy_iter():
    obj = None
    def __iter__():
       nonlocal obj
test_proxy_iter()

```

Error report:

> (base) xxm@xxm-System-Product-Name:~$ jython test.py 
> "my" variable $jythonHome masks earlier declaration in same scope at /usr/bin/jython line 15.
>   File "test.py", line 5
>     nonlocal obj
>             ^
> SyntaxError: mismatched input 'obj' expecting NEWLINE

Expected output:

> It works well as CPython does

System:

> Ubuntu 16.04
> Jython 2.5.3  
> OpenJDK 64-Bit Server VM (Private Build) on java1.8.0_292
>

**Comment by Stewori** [comment]
The ``nonlocal`` statement was introduced in Python 3, see https://www.python.org/dev/peps/pep-3104/. Existing Jython releases are still Python 2.

**Comment by xiaxinmeng** [comment]
I see. Thank you!
