### ISSUE TITLE
array.array itemsize and serialization anomalies for unsigned types

### ISSUE THREAD

**Issue by TheMatt2** [jython/jython#119]
In Jython's `array` module, the `itemsize` reported for unsigned types is double the size for signed types.
Furthermore, the operations on `array.array()` do not respect this larger size, but instead ingests data as of the signed variant had been specified.

Meanwhile having a size larger than normal is allowable according to the [`array.array()`](https://docs.python.org/2.7/library/array.html?highlight=array#module-array) docs, this size is still incorrect, since Jython is actually expecting the smaller size.

Steps to Reproduce:
Type the following into Jython, or run the contained script.
Observe that signed and unsigned types differ in size.
```
>>> array.array('b').itemsize # Size of a signed byte
1
>>> array.array('B').itemsize # Size of unsigned byte (incorrect; should be 1)
2
>>> array.array('h').itemsize # Size of signed short
2
>>> array.array('H').itemsize # Size of unsigned short (incorrect; should be 2)
4
>>> array.array('i').itemsize # Size of signed int
4
>>> array.array('I').itemsize # Size of unsigned int (incorrect; should be 4)
8
```

Observe that the array class does not respect this size.
Also, observe that if `array.byteswap()` is called, the array will enter an invalid state.
Type this into the interpreter:
```
>>> arr = array.array('B')
>>> arr.itemsize # Observe the incorrect size
2
>>> arr.fromstring('\x10\x00') # If size = 2, this should format to a single value
>>> arr
array('B', [16, 0]) # Actually is formatted as two values
>>> arr.byteswap() # Enters invalid state
>>> arr
array('B', [4096, 0]) # 4096 is larger than possible byte
>>> arr.tolist()
[4096, 0] # again, larger than possible byte
>>> arr.tostring()
'\x00\x00' # This does not match other representations
```

Here is a script that will automatically check all of the types `array.array` supports for this bug.
https://gist.github.com/TheMatt2/7d3646db897ed61da39ed3b566d51f91

System
Ubuntu 20.04.2 LTS
Jython 2.7.2b2-DEV (uncontrolled:+, Jan 12 2020, 08:32:17) 
[OpenJDK 64-Bit Server VM (Ubuntu)] on java11.0.11

**Comment by jeff5** [comment]
This is old code. (I may have added the buffer interface and reformatted, but the logic is old). The divergence in sizes from CPython appears to be a considered decision(see https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/core/PyArray.java#L648), probably with the idea of avoiding sign-extension problems. The Javadoc has not kept up.

However, if it is inconsistent between parts of the code, that's a bug.

**Comment by TheMatt2** [comment]
I see the types in the source code indicate the unsigned types use the next largest, but that is an implementation detail.

The source seems to show the intended _effective_ size is the same as the signed counter part.

This can be seen a little further along in the source code

https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/core/PyArray.java#L1090

Even though the `'I'` type is the size of a long, the literal is read as a size of an int.
So the `itemsize` parameters should be visible as in the original post, not as in how `PyArray` happens to overcome Java's lack of unsigned types.

**Comment by TheMatt2** [comment]
This handling actually exposes another bug in `array`.

`'L'`, which I had thought worked properly, does not allow values to be loaded that are a full 8 bytes in size.
```
Jython 2.7.2b2-DEV (uncontrolled:+, Jan 12 2020, 08:32:17) 
[OpenJDK 64-Bit Server VM (Ubuntu)] on java11.0.11
Type "help", "copyright", "credits" or "license" for more information.
>>> import array
>>> x = array.array('L')
>>> x.itemsize
8
>>> val = (1 << (8 * 8)) - 1
>>> val
18446744073709551615L
>>> x.fromlist([val])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: long int too large to convert
```

This snippet works on Python 2.7.18 and Python 3.8.10, but fails in Jython.

`2 ** 64 - 1` should fit in an unsigned long, but it does not.

**Comment by jeff5** [comment]
I poked at this some more.

It is not incorrect that the `itemsize`should differ from CPython's. The documentation makes it clear that this may vary according to the implementation of C in use. Hmmm ... strong code smell there.

The treatment of unsigned types as double their natural width is surprising, and I think that has led to difficulties.  As you observe, we have to compensate for the item size when we convert to a stream (e.g. https://github.com/jython/jython/commit/67847997e8f53b264be86509397ce06c6a3e118a).

The motivation is surely that at the Java level one can access the storage array as itself and get the right value automatically. This is amazingly simple in its original version:
https://github.com/jython/jython/blob/e4d0b91bec36357a25baf42e028d5e5442bfe2c8/org/python/core/PyArray.java#L70-L72
However, the simplicity is deceptive. `Py.java2py` has to do a lot of work at run-time to work out how to turn an `Integer` into a `PyInteger`, where a less elegant`case` statement could get there in one jump.

So there is a case for aligning this to expectations, if it doesn't break too much else.

Too much is public in Jython, as a way of making it visible between our own packages, so it is difficult to know whether this kind of thing is internal or has become API. It doesn't much poke through to the Python level if the tests are to go by.

**Comment by jeff5** [comment]
I'm re-working this to address problems raised here. There's quite a lot in this code that doesn't bear close inspection. I can make it a lot clearer and hopefully more correct.

The representation of data in the array will be more like you'd expect, but I think it possible this will break some uses where the array is accessed from a Java application.

**Comment by jeff5** [comment]
I can do this now:
```
PS Jython-2> dist\bin\jython
Jython 2.7.3a1-DEV (heads/master-dirty:7a0731565, Sep 27 2021, 07:11:57)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java11.0.9
Type "help", "copyright", "credits" or "license" for more information.
>>> import array
>>> x = array.array('L', [2**64-1])
>>> x
array('L', [18446744073709551615L])
>>> x.fromlist([2**64])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: unsigned long array value is more than maximum
>>> y = array.array('B', '\x10\x00')
>>> y
array('B', [16, 0])
>>> z = array.array('H', '\x10\x00')
>>> z
array('H', [4096])
>>> z.byteswap()
>>> z
array('H', [16])
```

`byteswap()` is problematic for 'u' arrays since it produces code points that Java cannot turn into strings, so we cannot turn them into `PyUnicode`, when the array elements are accessed.
```
>>> u = array.array('u', u'hello')
>>> u
array('u', u'hello')
>>> array.array('I', u.tostring())
array('I', [104, 101, 108, 108, 111])
>>> u.byteswap()
>>> array.array('I', u.tostring())
array('I', [1744830464, 1694498816, 1811939328, 1811939328, 1862270976])
>>> u
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
java.lang.IllegalArgumentException: 1744830464
        at java.base/java.lang.StringUTF16.toBytes(StringUTF16.java:219)
        at java.base/java.lang.String.<init>(String.java:328)
        at org.python.core.PyArray.tounicode(PyArray.java:1759)
       ...
```
