### ISSUE TITLE
`array.array('z')` is undocumented

### ISSUE THREAD

**Issue by TheMatt2** [jython/jython#120]
`array.array('z')` appears to be a special type that represents an array of boolean values.

This typecode is unique to Jython, as it neither exists, nor is documented in [Python 2](https://docs.python.org/2.7/library/array.html) or [Python 3](https://docs.python.org/3.10/library/array.html).

[Jython's old docs](https://www.jython.org/jython-old-sites/docs/library/array.html) don't make mention of it either.

The `help()` function in Jython doesn't show its existence either.

No variation of using `help()` brings any documentation for `array.array`.

```
import array
help(array)
help(array.array)
help(array.array.typecode)
```

The only reference I have found to it is within the Jython source code itself.
https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/core/PyArray.java#L610

While this custom variation from the Python specification seems to have a purpose, I am not sure how anyone would know to use it, or how to avoid writing code that is silently broken by it (since it differs from all other typecodes as it creates boolean values).

**Comment by TheMatt2** [comment]
`'z'` is also not even present in the error message for typecodes with the array class, seemingly just not present.

```
Jython 2.7.2b2-DEV (uncontrolled:+, Jan 12 2020, 08:32:17) 
[OpenJDK 64-Bit Server VM (Ubuntu)] on java11.0.11
Type "help", "copyright", "credits" or "license" for more information.
>>> import array
>>> a = array.array('A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: bad typecode (must be c, b, B, u, h, H, i, I, l, L, f or d)
```

**Comment by jeff5** [comment]
```
PS Jython-2> dist\bin\jython
Jython 2.7.3a1-DEV (heads/master-dirty:17859c64c, Nov 20 2021, 16:56:07)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_271
Type "help", "copyright", "credits" or "license" for more information.
>>> import array
>>> a = array.array('A')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: typecode must be b, B, h, H, i, I, l, L, f, d, c, u, z or a Java class
>>> array.array('z', (0,1,2))
array('z', [False, True, True])
```
Also: https://github.com/jython/jython/blob/50729e600faa99454a5c652fde285f3830611126/src/org/python/core/PyArray.java#L131-L136
