### ISSUE TITLE
Outdated OpenPGP Public Key Info

### ISSUE THREAD

**Issue by iontodd** [jython/jython#124]
On the Download page there is a key server referenced to confirm signatures of the software being downloaded, however, this key server appears to be deprecated. In addition, there seems to be some discussion on whether key servers are the best way to host and share GPG keys.

Is there a plan to let users confirm the validity of their jython downloads going forward?

<img width="676" alt="Screenshot 2021-08-10 at 08 02 28" src="https://user-images.githubusercontent.com/5908733/128816119-bdd7d5f3-9c5d-49b2-8eb4-ec4cc88c8b0e.png">

**Comment by jeff5** [comment]
I think that key server pool has evaporated, for reasons explained in [this post](https://gist.github.com/rjhansen/67ab921ffb4084c865b3618d6955275f). I find that keyserver.ubuntu.com knows me:

    gpg -v --keyserver hkps://keyserver.ubuntu.com --recv-keys 875C3EF9DC4638E3

However, given rjh's explanation, I haven't figured out whether ubuntu is part of the poisoned pool (but still running for now), or somehow unaffected, or represents a new clean pool.

I think that is the incantation we should be giving people today. Thanks for raising it.

**Comment by jeff5** [comment]
Now correct in live, until it's wrong again.
