### ISSUE TITLE
http connection hangs

### ISSUE THREAD

**Issue by caraiz** [jython/jython#13]
Im making a http connection with method POST to send a file (using httplib/urllib2) and if it is over 64KB (approximately) the response is never received and the code hangs forever.

It happens from jython-standalone-2.7.1-rc2.jar, if i use jython-standalone-2.7.1b3, it works fine.
I have done some tests and if i overwrite the _socket.py with the 2.7.1b3 version, then it works, so i suppose is a different implementation in newer versions which cause the problem.

Also i had check the TCP packets with Wireshark and the response packets from the server is never received, so seems problem when sending the data.

**Comment by lins05** [comment]
May I ask what's the status of this issue (as of the latest 2.7.3 release)? There is a recent PR https://github.com/jython/jython/pull/185 related, but I don't think that addresses this issue, right?

**Comment by jeff5** [comment]
I think it does address this and maybe should have closed it. It is in the 2.7.3 release. What is your experience in use?

You will see that it has a complaint against it, although that is about an encoding side effect, not buffer sizes.
