### ISSUE TITLE
Jython 2.7.2 ImportError: No module named <my_package_name> when running `import com.<my_package_name>`

### ISSUE THREAD

**Issue by cesarcoatl** [jython/jython#131]
After reading @jeff5's [notes](https://inside-jython.readthedocs.io/en/latest/import.html) on how `import` works, I still have a question regarding an issue I am facing.

I have created a "stubs" [library](https://github.com/thecesrom/Ignition/tree/jython), and recently I added the `com` package and it seems that `jython` is having trouble importing any module under that package. 

The `com` package looks like this:
```bash
$ tree
└── src
    ├── com
    │   ├── __init__.py
    │   └── inductiveautomation
    │       ├── __init__.py
```

And I have placed the following code under `inductiveautomation/__init__.py` just for checking:

```python
from __future__ import print_function


def dummy():
    print("test")

```

But this happens when I run `jython -v`:
```bash
$ jython -v
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[OpenJDK 64-Bit Server VM (Azul Systems, Inc.)] on java11.0.12
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; sys.path.extend(['/Users/thecesrom/github/Ignition/jython', '/Users/thecesrom/github/Ignition/jython/src'])
>>> import com
org.python.import CONFIG import com # as java package
>>> dir(com)
['__name__', 'apple', 'azul', 'inductiveautomation', 'kenai', 'sun', 'xhaus', 'ziclix']
>>> import com.inductiveautomation
org.python.import CONFIG import encodings.utf_8 # precompiled from /Users/thecesrom/.pyenv/versions/jython-2.7.2/Lib/encodings/utf_8$py.class
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named inductiveautomation
```

Calling `dir(com)` does list `inductiveautomation`, but `jython` appears to be expecting it to be elsewhere.

Is it that `com` should not be used?

Thanks

**Comment by deepali1332** [comment]
http://13.235.238.113/cart/cart.php

**Comment by jeff5** [comment]
There is a problem when a Java package and a Python package share the same name. The Jython book says "don't do it". https://jython.readthedocs.io/en/latest/ModulesPackages/#sys-path

Unfortunately it is absolutely the natural thing to do and sometimes you have no choice. #64 

The object that represents a Java package in the interpreter, and a Python module are different types. They have different rules about the visibility of members. So what seems natural may be a contradiction ... or I'm not thinking hard enough ... or it needs syntactic support.

I think it is not impossible for the natural thing to be made to work (in a Jython 3 re-think, say) but it is a large re-write to get there from the current package manager.

**Comment by cesarcoatl** [comment]
Thanks for your response.

> Naming Python Modules and Packages ———————————-
> 
> Developers coming from Java will often make the mistake of modeling their Jython package structure the same way that they model Java packages. Do not do this. The reverse url convention of Java is a great, I would even say a brilliant convention for Java. It works very well indeed in the world of Java where these namespaces are merged. In the Python world however, where modules and packages display the winner take all semantic, this is a disastrous way to organize your code.
> 
> If you adopt this style for Python, say you are coming from “acme.com” so you would set up a package structure like “com.acme”. If you try to use a library from your vendor xyz that is set up as “com.xyz”, then the first of these on your path will take the “com” namespace, and you will not be able to see the other set of packages.

I guess in this case it would be better to import the jar file instead of mocking it in Python.

Thanks, @jeff5.
