### ISSUE TITLE
Jython 2.7.2: AttributeError: 'null' object has no attribute 'name'

### ISSUE THREAD

**Issue by orionll** [jython/jython#135]
We upgraded from Jython 2.7.0 to 2.7.2 and our code doesn't work now. Here is a minimal example:

```
// MyPythonObject.java

import org.python.core.PyObject;
import org.python.expose.ExposedClassMethod;
import org.python.expose.ExposedType;

@ExposedType
public class MyPythonObject extends PyObject {

    @ExposedClassMethod
    public void hello() {
        System.out.println("Hello");
    }
}
```

```
// Main.java

import org.python.core.PyStringMap;
import org.python.util.PythonInterpreter;

public class Main {
    public static void main(String[] args) throws Exception {
        PythonInterpreter.initialize(null, null, new String[0]);
        PyStringMap map = new PyStringMap();
        PythonInterpreter pythonInterpreter = new PythonInterpreter(map);
        map.__setitem__("myobj", new MyPythonObject());
        pythonInterpreter.exec("myobj.hello()");
    }
}
```

The code runs fine on Jython 2.7.0 and 2.7.1:
```
Hello
```

However, it fails on 2.7.2:
```
Exception in thread "main" Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'null' object has no attribute 'hello'
```

Any ideas why this happens? Is it something we do wrong or is it a bug in Jython?

I tried Java 8, 11 and 17 with the same result.

**Comment by jeff5** [comment]
Almost certainly a bug. Thanks for the minimal example. Assumig this reproduces it reliably, this should make it easy to track down.

**Comment by jeff5** [comment]
I can reproduce this.

The exposer annotations are used to create built-in Python objects in the interpreter. They cause additional code to be generated when processed during our build, but the annotation processor is not supported for general use.

You do not need them simply to use a class defined in Java from a program written in Python.

I took the annotations out. It worked. Now I'm kicking myself for not seeing this immediately. 🤦
```
PS 135> javac -classpath ".;C:\Jython\2.7.2\jython.jar" *.java
PS 135> java -classpath ".;C:\Jython\2.7.2\jython.jar" Main
Hello
```
