### ISSUE TITLE
Security vulnerability through commons-compress

### ISSUE THREAD

**Issue by siddhu741** [jython/jython#137]
The affected package is upgraded in the commit https://github.com/jython/jython/commit/f64df54fd35fab00519cc55821df90f4fbc5dcf4. 

If you can please provide a new Jython version with this commit, it will be helpful. 

Thank you

**Comment by jeff5** [comment]
Our release cadence is a bit slow, but yes.

**Comment by siddhu741** [comment]
Sure, thank you for the response. I will wait for the next release.

**Comment by Bastian-Graebener** [comment]
@jeff5 
Is there a chance you could give an estimate on when the next release containing this fix is planned?
Thank you.

**Comment by Mochis** [comment]
Hi, could be possible a release 2.7.3 with this? Our security scanners are complaining about that and we don't know if we must wait for a fix or generate our own jar with the changes.

Thank you very much.

**Comment by jeff5** [comment]
I was reluctant to answer this without a solution to #97, as Jython without `pip` seems a poor thing. Now I believe I have a solution, I think a beta for Easter is reasonable.

A number of people have kindly contributed patches that I would like to include.

I haven't looked to see if any other difficult issues ought to be blockers. (If it's a vulnerability solved by updating a JAR, that's easily dealt with.)

**Comment by jeff5** [comment]
Nothing additional to do here as the change is already in, and 1.21 is still the latest version.
