### ISSUE TITLE
jython-standalone question

### ISSUE THREAD

**Issue by niuzhi** [jython/jython#143]
The java program calls the python script through jython-standalone.jar, but the module is always not found. How to import the third-party modules in the python script, such as http, jinja2, markupsafe, lark, etc.thanks

**Comment by jeff5** [comment]
`import` searches places on `sys.path`, so you add a place to that or put modules in `site-packages` for your user. Here I have put a package `pkg` containing a module `a` in my `site-packages`:
```
PS 272-trial> java -jar .\kit\jython-standalone.jar
Jython 2.7.2 (v2.7.2:925a3cc3b49d, Mar 21 2020, 10:03:58)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_271
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
['', 'C:\\Users\\Jeff\\Documents\\Jython\\272-trial\\kit\\Lib', 'C:\\Users\\Jeff\\Documents\\Jython\\272-trial\\kit\\jython-standalone.jar\\Lib', '__classpath__', '__pyclasspath__/', 'C:\\Users\\Jeff\\.local\\lib\\jython2.7\\site-packages']
>>> import pkg
Executed:  C:\Users\Jeff\.local\lib\jython2.7\site-packages\pkg\__init__$py.class
>>> from pkg import a
Executed:  C:\Users\Jeff\.local\lib\jython2.7\site-packages\pkg\a$py.class
>>>
```

`pip` no longer supports Jython and 2.7 compatibility of things you use will be a challenge generally.

**Comment by niuzhi** [comment]
@jeff5  thank you
I use the java program to call the python command and it prompts that the lark module cannot be found, but I use the java -jar standalone.jar interactive command to run the same code but no error occurs. What is the reason for this? thanks

![image](https://user-images.githubusercontent.com/33443724/142659730-6151a36d-a19d-4f69-8a1b-320459146e55.png)

![image](https://user-images.githubusercontent.com/33443724/142659820-665ad90a-8d04-4192-b513-fae3ed65c534.png)


import jinja2 has error

If every module needs to modify the source code, the workload is huge.

![image](https://user-images.githubusercontent.com/33443724/142661511-a3ce9025-e650-4680-a4c7-918346522133.png)

**Comment by jeff5** [comment]
In the second image it is evident you are expecting Jython 2 to compile Python 3, and I'm sorry -- you're out of luck. Jython 3 is active but will take a while to deliver.

I'm not sure about the first image. It may be that Jython has turned the compilation error into a no-such-module, but that's a poor diagnostic.
