### ISSUE TITLE
How can I get code hints in Pycharm?

### ISSUE THREAD

**Issue by lemisky** [jython/jython#145]
I tried to find the answer, but found nothing. I'm a newbie to Jython, I don't know if there are any code hints.

```python
# coding=utf-8
from __future__ import print_function

from java.util import Random

r = Random()
x = r.nextInt()
print(x)

```

An error is prompted, but it runs normally.

![image](https://user-images.githubusercontent.com/35125624/144748446-9c7631aa-3800-4361-90e1-9ddb9c10bb54.png)

**Comment by lemisky** [comment]
I look forward to any answer 🌹

**Comment by DavidPerezIngeniero** [comment]
I think PyCharm doesn't support Jython.

**Comment by jeff5** [comment]
There may be other places to ask, but I think no-one here knows.
