### ISSUE TITLE
python execution

### ISSUE THREAD

**Issue by tawonat7** [jython/jython#149]
does Jython allow you to execute To execute Multiline code from a sinle string

**Comment by jeff5** [comment]
Seems to. https://github.com/jython/jython/blob/50729e600faa99454a5c652fde285f3830611126/tests/java/org/python/util/InterpreterTest.java#L55-L60

Is this the context of your question?

**Comment by tawonat7** [comment]
> Seems to.
> 
> https://github.com/jython/jython/blob/50729e600faa99454a5c652fde285f3830611126/tests/java/org/python/util/InterpreterTest.java#L55-L60
> 
> Is this the context of your question?

yes yes it is
