### ISSUE TITLE
References to equal bound method objects get different ids

### ISSUE THREAD

**Issue by jonasbjurel** [jython/jython#161]
```
class foobar:
   def __init__(self):
      print(id(self.bar))
      print(id(self.bar))
   
   def bar(self):
      pass

barfoo = foobar()

>>> import foobar
2
3
>>>
````

?????

Jython 2.7.2

**Comment by jeff5** [comment]
CPython 2.7.18:
```
>>> class C:
	def m(self): pass
	
>>> x = C()
>>> a = x.m
>>> b = x.m
>>> a is b
False
>>> a == b
True
>>> type(a)
<type 'instancemethod'>
```
When `m` is a method of a class `C` and `x` is an instance of `C`, the expression `x.m` creates a bound method object each time it is evaluated. `a` and `b` are distinct objects, but equal.

In CPython, if you don't keep a reference, the object is garbage-collected immediately so the `id` is available for re-use. (In CPython ids are memory addresses.)

If you create such an object in Jython and don't keep a reference, it may not be garbage-collected immediately, so another object must take a new `id`. (In Jython, ids are assigned one-up.)
