### ISSUE TITLE
Hope to release a new version

### ISSUE THREAD

**Issue by lalicw** [jython/jython#163]
Since the release of the last version,  the  community have fixed a lot of bugs and solved a lot of problems. 
First thanks for the efforts of relevant people, all users have benefited.
Second, now two years passed, hope to release a new version that includes these solved problems,  is that possible?

**Comment by jeff5** [comment]
@lalicw I agree. A beta release is in plan for April (Easter), and a full release after that (if all's ok).

**Comment by lalicw** [comment]
thanks, i really appreciate that

**Comment by joeshannon** [comment]
Would it be possible for #128 and/or #129 to be considered for this release?
We would be really keen to update Jython but are currently blocked due to #93.

**Comment by lalicw** [comment]
thanks for u efforts~
