### ISSUE TITLE
Jython can not parse python script

### ISSUE THREAD

**Issue by Aukstkalnis** [jython/jython#164]
Hi. I am trying to use Jython with esptool.py file and Jpython complains about syntax.

SyntaxError: ("mismatched input 'as' expecting COLON", ('.\\tools\\JythonScripts\\esptool\\esptool.py', 117, 37, '')):
```
except (FatalError, OSError) as err:
```
SyntaxError: ("no viable alternative at input '='", ('.\\tools\\JythonScripts\\esptool\\esptool.py', 197, 35, '')):
```
print("\r%s" % message, end='\n' if last_line else '')
```
SyntaxError: ("no viable alternative at input '='", ('.\\tools\\JythonScripts\\esptool\\esptool.py', 368, 47, '')):
```
print('Detecting chip type...', end='')
```
SyntaxError: ("no viable alternative at input ''''", ('.\\tools\\JythonScripts\\esptool\\esptool.py', 369, 99, '')):
```
res = detect_port.check_command('get security info', ESPLoader.ESP_GET_SECURITY_INFO, b'')
```
There is more but they are similar. Is these problems was already fixed? If no, how to workaround them? I am not Python and Java developer so I don't know how to workaround them.

**Comment by jeff5** [comment]
Jython is an implementation of Python 2.7. You're expecting Python 3. (Working on it.)
```
try:
    raise TypeError()
except (TypeError, ValueError) as err:
    print "Boo:", repr(err)
``` 
worked for me in 2.7.3a1 (next release).
