### ISSUE TITLE
use my own class for argument in python

### ISSUE THREAD

**Issue by zaze06** [jython/jython#171]
So I have my class `Foo.java` that I want to use as a parameter for function `test` in python. how would I cast an object of `Foo` to a PYObject to be passed to the function?

**Comment by jeff5** [comment]
No cast. It just works. :)
```
>>> from java.util import ArrayList
>>> a = ArrayList()
>>> def test(x): print x
...
>>> test(a)
[]
>>> a.addAll(range(10))
True
>>> test(a)
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
For your own class, `Foo.class` has to be on the class path when you launch Jython, but then you Python-import the package that contains it, like it was a module. `Foo` will be a type, so you just instantiate by calling.

Magic.

**Comment by zaze06** [comment]
well, I meant in the way from java, so I call the function test from java. but I think i figured it out, just need to make a `PythonInterpreter`
