### ISSUE TITLE
Getting Jython to run in a project using Gradle

### ISSUE THREAD

**Issue by zaze06** [jython/jython#173]
So when I try to run some python code I get this

```
ImportError: Cannot import site module and its dependencies: No module named site
Determine if the following attributes are correct:
  * sys.path: [/home/zacharias/IdeaProjects/Twitch/build/libs/Lib, __classpath__, __pyclasspath__/]
    This attribute might be including the wrong directories, such as from CPython
  * sys.prefix: /home/zacharias/IdeaProjects/Twitch/build/libs
    This attribute is set by the system property python.home, although it can
    be often automatically determined by the location of the Jython jar file

You can use the -S option or python.import.site=false to not import the site module
```

I don't have the `libs` folder in my project so should I add `-S` as a program argument is where should I add it?

**Comment by jeff5** [comment]
Quite often, the first element of `sys.path` is the current working directory. In a healthy console session, mine is:
```
>>> sys.path
['', 'C:\\Jython\\2.7.2\\Lib', '__classpath__', '__pyclasspath__/', 'C:\\Users\\Jeff\\.local\\lib\\jython2.7\\site-packages', 'C:\\Jython\\2.7.2\\Lib\\site-packages']
```
I installed to `C:\\Jython\\2.7.2`.  Clearly yours is a bit short.

Now, you're doing this from a `PythonInterpreter`, and I would guess, under an IDE or build tool like Gradle. `build/libs` looks like where that kind of tool expects to deliver a JAR of your code and run it. The `build` tree is almost certainly that target, so `libs` won't be in your project.

I think Jython can't guess where home is. I think a good place to start is to define the JVM property `python.home` to the place where the Jython JAR is found.

What JAR are you using? How do you include it in your project?

**Comment by zaze06** [comment]
Hi, I'm using version `2.7.2` of Jython and I'm including it like this
```
dependencies{
    // Other dependencies
    implementation 'org.python:jython:2.7.2'
}
```
in my `build.gradle` file

Notes:
- Jython is included in the exported jar so if we can use that Jython for ease on the user end
- I'm using Ubuntu on development end but the user will most likely be using windows(11) if that is needed for a solution

**Comment by zaze06** [comment]
so I added the `Jython-standalone-2.7.2.jar` to the `libs` folder and now it works, etleas on the development end. I also changed it so it uses the standalone jar as the python library.
so now my `build.gradle` so now it looks like this
```
dependencies {
    //other librarys
    implementation (name: 'jython-standalone-2.7.2', ext: 'jar')
}
```

**Comment by jeff5** [comment]
I'm glad that's beginning to work for you.

We started producing a "jython-slim" JAR in 2.7.2 that contains just our code and the Python libraries, for use with Gradle and Maven. The idea was that users could control (e.g. for version) their own dependencies. (The age of the uber-JAR is over.)

There's an "application" plug-in for Gradle (since 6.8, I think) that packages your code and its dependencies to simplify deployment. I upgraded a simple demo of the slim JAR to a recent Gradle to get this to work and it was painless. Entire `gradle.build`:
```
// Applications importing the jython-slim JAR.
plugins {
    id 'application'
}
sourceCompatibility = '1.8'
targetCompatibility = '1.8'
version = '0.0.2'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.python:jython-slim:2.7.2'
}

application {
    mainClass = 'uk.co.farowl.jython.slimdemo.Simple'
}
```
So no special copying around of JARs. After `.\gradlew --console=plain assembleDist` I get a `.zip` that unpacks to everything you need and a script (`.bat` for me) to run it. `Simple.java` is just:
```
package uk.co.farowl.jython.slimdemo;
import org.python.util.PythonInterpreter;
public class Simple {
    public static void main(String[] args) {
        PythonInterpreter interp = new PythonInterpreter();
        interp.exec("print 6*7");
    }
}
```
Then after unpacking the `.zip`to `lib` and `bin`:
```
PS demo> .\bin\demo-jython-slim-gradle
42
```

**Comment by jeff5** [comment]
I changed the title because this is turning into a how-to others might be glad to find.

**Comment by zaze06** [comment]
thanks for your help. and yes renaming it might be a good idea
