### ISSUE TITLE
how to load a file as a module?

### ISSUE THREAD

**Issue by zaze06** [jython/jython#174]
So I have my file `shared.py` that has some functions that I need for other python files I have `from shared import *` in the files but the module doesn't load in.

what I have tried:
- `PythonInterpreter.eval(/*content of shared.py*/)` resulted in `SyntaxError` on `def`
- `PythonInterpreter.exec(/*content of shared.py*/)` resulted in `noModualError`(might have misrememberd)
- `PythonInterpreter.compile(/*FileReader pointed at shared.py*/)` resulted in `noModualError`(might have misrememberd)
- `PythonInterpreter.set("shared", PythonInterpreter.eval(/*content of shared.py*/))` esulted in `SyntaxError` on `def`

**Comment by jeff5** [comment]
Not much to go on here. If you don't want to show your real code, you'll have to make something up that fails the same way. 

You could try `PythonInterpreter.execfile` too. However, if an `import` is not working, I would look first at `sys.path`.

Also, wild guess, you do realise we only support Python 2.7 source? Python 3 is coming, but a way off.

**Comment by jeff5** [comment]
Also, answer to actual question in title, you can load a module with [imp.load](https://www.javadoc.io/static/org.python/jython-standalone/2.7.2/org/python/core/imp.html#load-java.lang.String-).

**Comment by zaze06** [comment]
I'm sorry for not giving my acual code, thuare i discribed what my issue was. And yes i know that the xurent version is 2.7 but i'm unsure what part of my memory of how python works is just 3.0 and works in 2.7 too. So `imp.load` will load a file as a module?

**Comment by zaze06** [comment]
got it to work using
```java
imp.createFromCode("shared", pi.compile(/*content of shared.py*/))
```
