### ISSUE TITLE
PyString with non-byte value in formatting of collections

### ISSUE THREAD

**Issue by jeff5** [jython/jython#192]
Sufficient to reproduce:
```
from java.lang import String
print [String(u"\u51fa")]
```
However, these work.
```
>>> print u"\u51fa"
出
>>> print String(u"\u51fa")
出
```
Definitely closer to #190 than the circumstances of #20.

_Originally posted by @yogi1967 in https://github.com/jython/jython/issues/20#issuecomment-1166451040_

**Comment by yogi1967** [comment]
This is a real pain and catches me unawares. Testing doesn't help, as I typically don't have characters that will cause this. Pls fix. Thx.

**Comment by yogi1967** [comment]
Thanks for the fix!

**Comment by yogi1967** [comment]
Curious when 2.7.3 is targeted for release? Thanks

**Comment by jeff5** [comment]
> Thanks for the fix!

I thought it worth trying to get into 2.7.3.

It shaves a bit more off the speed of Jython :(. The same test, whether a string fits into ascii/bytes, is now quite widespread in the code base. I'm looking where we can avoid the work.

> Curious when 2.7.3 is targeted for release? Thanks

We're very close to a beta of that. (Next week?) I think we have reached acceptable quality.

**Comment by yogi1967** [comment]
Hi Jeff, could you also fix this too please?

You will see that line 5 is fine, lines 6 shows garbage, line 7 errors.. All trying to do the same thing... I always have to do this to avoid `"%s" %(theStr)` instead of str()
```
from javax.swing import JOptionPane, JLabel
from java.lang import String
euroSymb=String(u"\u20ac")
gbpSymb=String(u"\u00A3")
JOptionPane.showMessageDialog(None, JLabel("Symbols: %s %s" %(euroSymb, gbpSymb)), "test", JOptionPane.INFORMATION_MESSAGE, None)
JOptionPane.showMessageDialog(None, JLabel("Symbols: " + str(euroSymb)+str(gbpSymb)), "test", JOptionPane.INFORMATION_MESSAGE, None)
print "Symbols: " + str(currSymb) + str(gbpSymb)
```

**Comment by jeff5** [comment]
> Hi Jeff, could you also fix this too please?

This is discussed on #195.
