### ISSUE TITLE
Suspected memory leak (PyType and PyModule)

### ISSUE THREAD

**Issue by robin-cs** [jython/jython#203]
I have a application using jyphon 2.7.2 to execute python script, and found that some memory leak in it. following picture is generated by eclipse MAT 
![image](https://user-images.githubusercontent.com/87006407/185564191-9f476323-62ae-4e5a-a8ef-068bbb6b8890.png)

**Comment by jeff5** [comment]
That is quite a lot of instances. If you have a simple application to reproduce it, that would help. How is it with the current beta 2.7.3b1?

Are you perhaps creating (and destroying) a large number of Python interpreters? I can see how this might result in garbage collection of the last reference to (say) the entire type system or system state.

**Comment by robin-cs** [comment]
thanks @jeff5 , I have resolved it, as your suggesstion, Application creating large number of Python interpreters.

**Comment by jeff5** [comment]
I'm glad my (uncannily good) guesswork was helpful.

**Comment by jeff5** [comment]
... forget that (brain fade).
