### ISSUE TITLE
IllegalArgumentException: where `char` method returns non-byte value

### ISSUE THREAD

**Issue by yogi1967** [jython/jython#204]
Another one of these errors...  Caused when running this code on this line:
`_groupingCharSep = decimalSymbols.getGroupingSeparator()`

```
from java.text import DecimalFormat
decimalFormat = DecimalFormat.getInstance()
decimalSymbols = decimalFormat.getDecimalFormatSymbols()
_decimalCharSep = decimalSymbols.getDecimalSeparator()
_groupingCharSep = decimalSymbols.getGroupingSeparator()
print ord(_decimalCharSep)
print ord(_groupingCharSep)
print "decimal char '%s'" %(_decimalCharSep)
print "grouping char '%s'" %(_groupingCharSep)

```

```
Traceback (most recent call last): 
  File "<string>", line 5, in <module> 
at org.python.core.PyString.<init>(PyString.java:57) 
at org.python.core.PyString.<init>(PyString.java:70) 
at org.python.core.PyString.<init>(PyString.java:78) 
at org.python.core.Py.makeCharacter(Py.java:2044) 
at org.python.core.Py.makeCharacter(Py.java:2036) 
at org.python.core.adapter.ClassicPyObjectAdapter$5.adapt(ClassicPyObjectAdapter.java:70) 
at org.python.core.adapter.ExtensiblePyObjectAdapter.adapt(ExtensiblePyObjectAdapter.java:44) 
at org.python.core.adapter.ClassicPyObjectAdapter.adapt(ClassicPyObjectAdapter.java:131) 
at org.python.core.Py.java2py(Py.java:2064) 
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
```

Unfortunately, I cannot reproduce it myself, but the user's screen was setup like this.

![image](https://user-images.githubusercontent.com/22958485/185732153-27d555e3-a232-4bb8-82f1-3942d7c3ef6a.png)

I've seen something similar before with a nbsp character... But why is it failing on assigning to a variable? I'm not even print'ing it..?

Any ideas? I don't even know what code to run to interrogate the result to see what the problem is......

**Comment by jeff5** [comment]
You wouldn't have to do anything with it. The message is about trying to make a Python `str` from something that doesn't fit into a byte. Now, the return value from a Java function gets converted to a Python object in a wrapper around that function, so I think the problem most likely lies in the outdated assumption that a `char` return is a byte.

My first guess was going to be that it's the euro character. But as it's at `decimalSymbols.getGroupingSeparator()` (thanks for that clue), it's more likely to be what's in the "Regroupement" drop-down.

The error seems to occur in the set-up where you're just getting values from `java.text`. I expect those will reflect the user's locale. Is the dialogue you show a system one controlling that?

Thanks to #160, 2.7.3 will tell you what the offending character was. We have also fixed some places where it occurs (#20) but not all of them I bet.

**Comment by jeff5** [comment]
Java up to 11 (at least):
```
>>> from java.text import DecimalFormat, DecimalFormatSymbols
>>> from java.util import Locale
>>> decimalSymbols = DecimalFormatSymbols(Locale.FRENCH)
>>> decimalSymbols.getGroupingSeparator()
'\xa0'
```
That's a non-breaking space.

Java 17:
```
>>> from java.text import DecimalFormat, DecimalFormatSymbols
>>> from java.util import Locale
>>> decimalSymbols = DecimalFormatSymbols(Locale.FRENCH)
>>> decimalSymbols.getGroupingSeparator()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
        at org.python.core.PyString.<init>(PyString.java:57)
        at org.python.core.PyString.<init>(PyString.java:89)
        at org.python.core.Py.makeCharacter(Py.java:2061)
        at org.python.core.Py.makeCharacter(Py.java:2053)
        at org.python.core.adapter.ClassicPyObjectAdapter$5.adapt(ClassicPyObjectAdapter.java:70)
        at org.python.core.adapter.ExtensiblePyObjectAdapter.adapt(ExtensiblePyObjectAdapter.java:44)
        at org.python.core.adapter.ClassicPyObjectAdapter.adapt(ClassicPyObjectAdapter.java:131)
        at org.python.core.Py.java2py(Py.java:2081)
java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value: '\u202f'
```
That's a *narrow* non-breaking space, apparently.

**Comment by yogi1967** [comment]
That explains that.. I used to catch nbsp, but that was prior to java 17... It's easy to break.... Try this:

```
from java.text import DecimalFormat
g = u"\u0100"
print g, str(g), unicode(g), len(g)

df = DecimalFormat.getInstance()
dfs = df.getDecimalFormatSymbols()
dfs.setGroupingSeparator(g)
dfs.getGroupingSeparator()		# THIS WILL FAIL with java.lang.IllegalArgumentException
```

But even so, does this mean there's a bug in Jython? Shouldn't it somehow realise that it 'won't fit' (or whatever) and 'deal with it'....?

**Comment by jeff5** [comment]
In some places, we deal with similar problems by returning `unicode`, and that's probably the thing to do here. It would apply wherever a `char` is returned from any function. That would be quite an intrusive/risky change, so not make it into 2.7.3.

Could you work around this in your application by setting a byte-sized grouping separator?

**Comment by yogi1967** [comment]
I've worked around it... So no hurry for me.... Thanks

**Comment by yogi1967** [comment]
Yup. This is why I'm only now just hitting the problem....

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8274768

... but doesn't change the fact that Jython should 'cope' with it 😵‍💫👌👍

**Comment by jeff5** [comment]
Yes it should, so we'll keep it open to re-visit how we wrap methods with a `char` return value.
