### ISSUE TITLE
Incorrect method precedence with overloading and variable arity

### ISSUE THREAD

**Issue by tpoliaw** [jython/jython#221]
If a Java class has overloaded methods such as
```java
public class Demo {
    public void foo(int a, int b) {
        System.out.println("two ints");
    }
    public void foo(int... args) {
        System.out.println("vararg ints");
    }
}
```
Calling `demo.foo(1, 2)` from Java code gives `two ints` as expected but from jython code gives `vararg ints`. The same can be seen with constructors now that vararg constructors are supported.

**Comment by jeff5** [comment]
Thanks for finding. Worth a look before there's a 2.7.4.

**Comment by tpoliaw** [comment]
I had a look at this when we initially tried updating but couldn't find a way to fix it that didn't involve duplicating code in several places. I can upload the WIP change as a PR if it'd be any use. Is there any rough timescale of when you're hoping to release 2.7.4?

**Comment by jeff5** [comment]
Having neglected Jython 2 for a while, I'm thinking I should catch up with a 2.7.4. Maybe Christmas?

This has come up in #281 so we ought to try and correct it. Duplicated code doesn't sound like a fatal flaw, but also has a well-known treatment. Let's see the WIP PR. (PRs can be marked as draft.)

**Comment by tpoliaw** [comment]
I'd forgotten I was supposed to be looking at this so thanks for reminding me. I will try and dig out the progress I'd made so far - a few more eyes on it can only be a good thing.

**Comment by robertpatrick** [comment]
@tpoliaw one possible approach would be to change the `matches()` method to return the number of non-varargs arguments matched and have the caller always iterate through the entire list of matching methods/constructors, selecting the one with the highest number of matching arguments.  This is essentially what Java does.

**Comment by robertpatrick** [comment]
What can I do to help?

**Comment by tpoliaw** [comment]
I've opened #282 with my wip from last year. It would be interesting to see if that works and/or whether there are more cases that fall through the gaps. As @jeff5 said, this could really use a thorough set of tests.

**Comment by robertpatrick** [comment]
I will test it and let you know.  I am happy to write tests and actually looked into doing that already.  The thing that was tripping me up was how to create a custom Java class and use it from Python tests.  The current Java test seemed too limiting but I am happy to be convinced otherwise.

**Comment by tpoliaw** [comment]
Have a look at the existing `test_jyoverload.py` and associated `Reflection.java` class as they're are already set up to be accessible. I've already added a few extra cases for overloaded constructors but more can't hurt.

**Comment by robertpatrick** [comment]
@tpoliaw I cannot seem to get the unit tests to report assertion errors like I expect them to (which could be because I am doing something wrong).  After trying a bunch of different things, I decided to step back and just add a single line to an existing test (the last line below):

```python
class ComplexOverloadingTests(unittest.TestCase):

    def test_complex(self):
        o = Reflection.Overloaded()
        self.assertEqual(o(2.), "class java.lang.Double=2.0")
        self.assertEqual(o(1+2j), "class org.python.core.PyComplex=(1+2j)")
        self.assertEqual(True, False).    # Trying to see assertion error 
 ```

Yet, when I run `ant clean test`, the output does not report the assertion error.

```
...
     [exec] test_javashell
     [exec] test_jbasic
     [exec] test_joverload
     [exec] test_jser
     [exec] test_jser2
...
     [exec] test_xpickle -- skipping backwards compat tests.
     [exec] Use 'regrtest.py -u xpickle' to run them.
     [exec] test_xrange
     [exec] test_zipimport_jy
     [exec] test_zipimport_support
     [exec] test_zlib
     [exec] test_zlib_jy
     [exec] 387 tests OK.
     [exec] 2 tests skipped:
     [exec]     test_codecmaps_hk test_curses
     [exec] 1 test failed:
     [exec]     test_socket_jy
     [exec] 1 fail unexpected:
     [exec]     test_socket_jy
     [exec] Result: 1
...
test:

BUILD SUCCESSFUL
Total time: 13 minutes 48 seconds
```

 What am I missing?  Is there some better way to run the unit tests so that I can see the errors?

**Comment by yogi1967** [comment]
I had another one today. This the java:

```
    public DateRange(@Nullable Date start, @Nullable Date end) {
        this.startDateInt = DateUtil.convertDateToInt(start);
        this.endDateInt = DateUtil.convertDateToInt(end);
        this.calcNumDays();
    }

    public DateRange(int start, int end) {
        this.startDateInt = start;
        this.endDateInt = end;
        this.calcNumDays();
    }

    public DateRange(long start, long end) {
        this(new Date(start), new Date(end));
    }


```

Calling this with Jython int's causes the constructor with long parameters to be selected (not the int's). To call the right constructor, I have to call it with java.lang.Integer(value)'s.

Will this PR fix this too?

**Comment by tpoliaw** [comment]
@yogi1967 I think that is a different issue so won't be affected by the PR. This one is about vararg methods taking precedence over non-vararg methods. I wouldn't be surprised if the same area of the code base is involved though - I've not looked in to how jython orders methods beyond number of arguments.

**Comment by tpoliaw** [comment]
@robertpatrick I'm not sure what's up with the tests. I remember some weirdness trying to get them to run last time but that I could definitely get them to fail when I was making the PR. I'll have another look or @jeff5 may know what's going on.

**Comment by yogi1967** [comment]
@tpoliaw - thanks. Whilst someone is in this code, can they fix this issue too?

**Comment by robertpatrick** [comment]
@yogi1967 - This behavior has existed for many years (since at least Jython 2.2.1) so fixing this may cause issues for existing scripts (i.e., making this a backward incompatible change).  Regardless, this conversion happens way before the method matching code that @tpoliaw is trying to fix is invoked.  By the time that it gets to this code, Jython has already converted the actual runtime argument to a long...

**Comment by jeff5** [comment]
> What am I missing? Is there some better way to run the unit tests so that I can see the errors

`dist\bin\jython -m test.test_joverload` works.

It was a surprise to find it doesn't produce output under `regrtest`, e.g.:
```
PS Jython-2> dist\bin\jython -m test.regrtest -v test_joverload
test_joverload
1 test OK.
```

Compared with other tests it lacks a `test_main()`. It did the trick to change your (@tpoliaw's) ending to:
```
def test_main():
    test_support.run_unittest(
        OverloadedDispatchTests,
        VarargsDispatchTests,
        ComplexOverloadingTests,
    )

if __name__ == '__main__':
    test_main()
```

with the appropriate `from test import test_support` near the top.

If you edit to add this @tpoliaw, could you get rid of the trailing white space too? (I have my IDE set to show it.)

**Comment by tpoliaw** [comment]
I don't think I set up the test_joverload module, only added to it with new cases. Having said that I can update it in the same PR if that's the new standard.

> with the appropriate from test import test_support near the top.

If that's the correct import it might explain why

```python
    try:
        import test_support
    except ImportError:
        unittest.main()
    else:
        test_support.run_unittest(OverloadedDispatchTests, VarargsDispatchTests, ComplexOverloadingTests)
````
is failing, The import is always raising the exception and it's ignoring the test_support call.

**Comment by tpoliaw** [comment]
> dist\bin\jython -m test.test_joverload works.

Worth pointing out that this runs on the versions of the tests in `dist` not the ones in `Lib` so needs `ant regrtest` (or whichever ant target copies files to dist directory) first.

**Comment by jeff5** [comment]
> > dist\bin\jython -m test.test_joverload works.
> 
> Worth pointing out that this runs on the versions of the tests in `dist` not the ones in `Lib` so needs `ant regrtest` (or whichever ant target copies files to dist directory) first.

Yes, you have to build Jython first. :/  Just plain `ant` will do that. 

(`ant regrtest` takes nearly an hour on my eco-machine.)

> The import is always raising the exception and it's ignoring the test_support call.

Maybe. I thought that, but it didn't seem to make the critical difference. However, I remember noticing this:
https://github.com/jython/jython/blob/e55e057637eb9fa30710f4c6720186a37c2b8974/Lib/test/regrtest.py#L617-L621

This is clearly just pulled in from CPython long time ago. Mostly I try to understand why, but sometimes I just do what I'm told ... :)

**Comment by tpoliaw** [comment]
>ant regrtest takes nearly an hour on my eco-machine

Ouch. I'll hold off complaining when it takes ten minutes on my laptop then.

Either way, I've added your suggestion to the PR and it seems to be failing successfully when trying to assert `1 == 2`.
