### ISSUE TITLE
JPasswordField no longer works due to 'bullet' echo char

### ISSUE THREAD

**Issue by bentoucour** [jython/jython#223]
Dear Jython dev team,

I have both exposure with Python and Java but I'm fairly new to Jython. I spent the past couple of days trying to upgrade Jython from 2.5 to 2.7 on a Jython app using swing and awt Java libraries. I faced an issue while dealing with JPasswordField objects. I concluded this is due to the fact **Jython can no longer handle the 'bullet' character used in standard for the JPasswordField component**.

If you call getEchoChar to get the character used to obfuscate each character of the password, you will get a: 

   `java.lang.IllegalArgumentException: Cannot create PyString with non-byte value: '\u2022'`

\u2022 is the java code for the bullet character.

As a workaround, I set the echo char to '*'... but it would be nicer to keep the default Java look and feel though.

This has been **reproduced with Java 8 and Java 11, and latest Jython 2.7.3**. It was working fine with Jython 2.5.

Here's a simple code to reproduce (uncomment the # to see the effect of the workaround):

```
from javax.swing import JFrame, JLabel, JPasswordField

f = JFrame('Password Field Example', defaultCloseOperation=JFrame.EXIT_ON_CLOSE, size=(300, 300), locationRelativeTo=None)
v = JPasswordField(bounds=(100,100,100,30))
l = JLabel('Password:', bounds=(20,100, 80,30))
#v.setEchoChar('*')
f.add(v)
f.add(l)
f.setVisible(True)
```

Regards,
Ben

**Comment by jeff5** [comment]
The root cause of this is (I'm fairly sure) #204
