### ISSUE TITLE
Veracode Security Vulnerability reported on jython-standalone 

### ISSUE THREAD

**Issue by scottpettyjohn** [jython/jython#230]
My team is being asked to remediate a vulnerability reported by Veracode:
‘Use of Hard-coded Cryptographic Key’ in the following classes in the Jython-Standalone. 
	•	JceETSIKeyWrapper.java: 1
	•	JceETSIDataEncryptor.java: 1

**Comment by scottpettyjohn** [comment]
I should add that we are using version 2.7.3

**Comment by jeff5** [comment]
I expect this is part of Bouncy Castle. We just bundle this library for a few of its functions, and to be honest, the way we do it undermines the trust you might put in it. (It knows this and protects you.) The standalone JAR is built to a legacy pattern.

The[ slim JAR distribution](https://search.maven.org/artifact/org.python/jython-slim/2.7.3/jar), in which you get copies in your own build from trusted sources, is a better way to get the dependencies.
