### ISSUE TITLE
Jython 2.7.3 minimum API level on Android

### ISSUE THREAD

**Issue by olprint** [jython/jython#237]
Jython 2.7.3 minimum API level on Android  is 26!
26 is too high.

**Comment by Stewori** [comment]
That's not relevant for Jython 2.x, see #66 and links therein.

**Comment by Stewori** [comment]
If Jython 3 is going to support Android, API level may indeed be worth consideration there. However, given Jython 3's current state, worrying about its Android API level probably qualifies as premature optimization.
