### ISSUE TITLE
Using == to compare strings in sys

### ISSUE THREAD

**Issue by myzhan** [jython/jython#238]
In PySystemState.java, there are two methods using == to compare strings.

```java
private static void checkReadOnly(String name) {
        if (name == "__dict__" || name == "__class__" || name == "registry" || name == "exec_prefix"
                || name == "packageManager") {
            throw Py.TypeError("readonly attribute");
        }
}

private static void checkMustExist(String name) {
        if (name == "__dict__" || name == "__class__" || name == "registry" || name == "exec_prefix"
                || name == "platform" || name == "packageManager" || name == "builtins"
                || name == "warnoptions") {
            throw Py.TypeError("readonly attribute");
        }
}
```

So I can bypass the check like this.

```python
import sys
from java.lang import String

p = String("exec_prefix")

sys.__setattr__(p, "xxx")
```

**Comment by Stewori** [comment]
The convention is that attribute names must be interned strings, so the `==` comparison is okay. Apparently, that convention is not enforced and neither is the access to private methods prohibited. I think it is important to notice that in Jython no attempt is made to prohibit this kind of hacking and it is not considered a security violation. The check for reserved names is to protect the average user from causing unintended damage. A user that knows how to hack around this like in your example is assumed to know the risks. That is much like all sorts of monkeypatching tolerated by CPython. Neither for CPython nor for Jython or even the JVM, secure sandboxing is a goal (security managers were recently deprecated). To some extend, it is even explicitly a non-goal, also see [the failure of pysandbox](https://lwn.net/Articles/574215/). It is no secret that Jython is not intended for running untrusted code. If security is required, it should be achieved by sandboxing on process-level.

**Comment by myzhan** [comment]
@Stewori Thanks!

**Comment by jeff5** [comment]
Re-opening because although we try to use interned strings in many places, the demonstration seems to confirm @myzhan is correct in this instance.

**Comment by Stewori** [comment]
Javadoc of `PyObject.__setattr__`with key of type `String` clearly indicates:
```
A variant of the __setattr__ method which accepts a String as the key. This String must be interned. 
```

That means, when the OP calls it with a non-interned String, essentially *undefined behavior* is invoked.
Enforcing the string interning (the only way I know would be to always call ``name.intern()`` at the beginning of ``PyObject.__setattr__``) would be costly. Changing that convention might be a backwards-incompatible change. Also, `equals`-based key comparison is more expensive and attribute lookup is a heavily used operation.

**Comment by jeff5** [comment]
@Stewori : Ah, good point. This isn't the `__setattr__` I thought it was.

I agree the specialisation is there for a reason and forcing it to intern would defeat the object. However, the breaking example is also perfectly allowable source in Python that does not quite do what it ought. If the specialisation were called something else, it would not capture the Python call, but then it would be less idiomatic Java API.

One could fix the particular example in `PySystemState`, but it probably exists elsewhere too. So I think you're right that we won't fix this (in Jython 2).

Evidently, the exposure of methods directly from the Java continues to be tricky. I haven't tackled this in Jython 3 yet. The example makes me think that an object (the `sys `module here) should either be:
- an intentional Python object, in which case its API is only the Python one, with exactly the right signatures, or
- a "discovered" object, in which the API is the reflected Java API and the Python API of `object`.

**Comment by Stewori** [comment]
Maybe, the proper solution would be to annotate the having-to-be-interned string arg with a type annotation ``@Interned``. Then one could use https://checkerframework.org/manual/#interning-checker and perhaps some IDEs support it as well. According to https://checkerframework.org/manual/#other-interning-annotations, we could declare an ``@Interned`` annotation ourselves so we would not have the checker framework as dependency and it would still be  compatible. Maybe other annotations supported by that framework are worth consideration for Jython as well, e.g. ``@NonNull``. An ``@Interned`` annotation may also improve generation of Java/Python bindings.

**Comment by jeff5** [comment]
It's supposed to do this:
```
>>> import sys
>>> sys.__setattr__("exec_prefix", "xxx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: readonly attribute
```

@myzhan tells us:
> I can bypass the check like this.
> 
> ```python
> import sys
> from java.lang import String
> p = String("exec_prefix")
> sys.__setattr__(p, "xxx")
> ```

Actually it's easier than that. One only needs not to use a constant:
```
>>> sys.__setattr__("_".join(("exec", "prefix")), "xxx")
>>> sys.exec_prefix
'xxx'
```

Both `PySystemState.__setattr__(String name, PyObject value) ` and `PyObject .__setattr__(PyString name, PyObject value) ` are exposed from `sys` by reflection. You might think the latter is the closer match, but by the mysteries of signature precedence in `ReflectedArgs`, the former is found first and coercion is applied from `PyString` to `String`.

I think an adequate solution is just to do the tests properly:
```
>>> sys.__setattr__("_".join(("exec", "prefix")), "xxx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: readonly attribute
```
We could have fun trying to determine the runtime cost of several approaches, but I used a `switch` in the hope the compiler would choose well for me. `sys.__setattr__` doesn't sound time critical.

I looked at [The Checker Framework](https://checkerframework.org/) which might save us from repeat mistakes. I quite like that. It would be a chunk of work to apply retrospectively.

**Comment by Stewori** [comment]
Agreed, changing this for ``sys.__setattr__`` is no big deal, at least not in terms of computation cost. However, wouldn't similar issues turn up in everything derived from ``PyObject``?  My concerns were about changing the semantics on ``PyObject`` level.

> 
```
import sys
from java.lang import String
p = String("exec_prefix")
sys.__setattr__(p, "xxx")
```
I could accept that, but indeed not the next one.
```
>>> sys.__setattr__("_".join(("exec", "prefix")), "xxx")
>>> sys.exec_prefix
'xxx'
```
Shouldn't ``"_".join(("exec", "prefix"))`` be producing a ``PyString`` instance?

> It would be a chunk of work to apply retrospectively.

Maybe consider it just for Jython 3 as an ongoing task during further development.

**Comment by jeff5** [comment]
> Agreed, changing this for `sys.__setattr__` is no big deal, at least not in terms of computation cost. However, wouldn't similar issues turn up in everything derived from `PyObject`?

I agree that is a consideration, but I didn't want to speculate (or go exploring right then). I *think* it matters that `PySystemState` exposes its members as Java. And this may be related to a comment that I have often looked at without understanding.
https://github.com/jython/jython/blob/117aa694e26bed0970fdb7187fbb5b1a999c4005/src/org/python/core/PySystemState.java#L66-L68

> Shouldn't `"_".join(("exec", "prefix"))` be producing a `PyString` instance?

It does, but we still end up calling the inherited `PySystemState.__setattr__(String, PyObject)` by reflection. 

> > It would be a chunk of work to apply [The checker Framework] retrospectively.
> 
> Maybe consider it just for Jython 3 as an ongoing task during further development.

That was my thought too.

**Comment by jeff5** [comment]
I delved a bit into where we use `==` with strings to special-case attribute access. It's not easy to pin down. There really are too many methods called `__(set|get|del|find)attr__` or something like it.

Most cases are within an implementation of `__findattr_ex__` and I am fairly sure that is only called with an interned string. If my theory is correct that `PyObject.__setattr__(String,PyObject)` is only accessible when a sub-class of `PyObject` is not an `@ExposedType` then `sys` is the only example.
