### ISSUE TITLE
Help finding a replacement for MessageSource

### ISSUE THREAD

**Issue by juniartisu** [jython/jython#239]
Hi,
Looks like MessageSource is being deleted in this issue https://hg.python.org/jython/rev/ec1b1e701776
Is there a replacement to it?
Thanks for your help in advance.

**Comment by jeff5** [comment]
That was a while ago. It looks like Jim was just simplifying our dependencies. If you needed a class from a JAR we don't include you could just include it on your path.

Dependencies may be better managed by using the Jython slim JAR (containing only what this project supplies) and then drawing down dependencies in your own project: depending on your process of course.
