### ISSUE TITLE
Document download/binaries location

### ISSUE THREAD

**Issue by clach04** [jython/jython#245]
The [GitHub jython](https://github.com/jython/jython/releases) release area/page is empty, most GitHub users would go check that first.

From email announcement I recommend https://search.maven.org/search?q=g:org.python be documented. Does making a change to the readme and the GtHub short summary make sense? I can do a PR for the former.

Email announcement:

> From: Jeff Allen <****> 
> Sent: Tuesday, September 13, 2022 11:18 PM
> To: Jython Developers <jython-dev@lists.sourceforge.net>; jython-users@lists.sourceforge.net
> Subject: [Jython-users] [Jython-dev] Jython 2.7.3 Released
> 
> The Jython Project is pleased to announce the general availability of Jython 2.7.3 at Sonatype. (https://search.maven.org/search?q=g:org.python)
> 
> This is a maintenance release that incorporates a number of bug-fixes, some kindly offered as PRs by users. It is identical to the recent release candidate (rc1) of about 2 weeks ago. Please report problems on the issue tracker (https://github.com/jython/jython/issues).
> 
> We are no longer inviting bugs at bugs.jython.org, which in due course will become read-only (as its python.org equivalent did this year). Bugs on the old tracker, whilst not entirely ignored, will not be migrated en masse to GitHub: if you care about one particularly, it would help us if you could raise it on GitHub, with a link to the b.j.o. entry.
> 
> Jeff

As always, thanks to everyone working on Jython to make it available! You rock! :-)

**Comment by Stewori** [comment]
Yes, I think the download location should be indicated in the readme. IMHO, please make a PR, however I would say the download location should point to ``https://www.jython.org/download``.
Thanks for your help!

**Comment by clach04** [comment]
I had time today to make a quick PR.https://github.com/jython/jython/pull/248
