### ISSUE TITLE
Duplicate readme files in git repo

### ISSUE THREAD

**Issue by clach04** [jython/jython#249]
I'm seeing 2 readme files, the markdown one that GitHub displays by default and a txt one that @jeff5 updated about a year ago.

* https://github.com/jython/jython/commits/master/README.md
* https://github.com/jython/jython/commits/master/README.txt

Discovered whilst working on #245.

I'm not sure what advantage the txt file has over the md.

**Comment by Stewori** [comment]
IIRC we switched to md to benefit from markup, but then noticed that the txt is the one packaged into the installer via ``ant jython-installer`` (or so). Since the file is rarely changed we went for keeping them in sync manually so far. Have they gotten out of sync? That's unfortunate :(

**Comment by jamesmudd** [comment]
If I remember correctly the `.txt` is used when building the Windows installer. The `.md` is used for github. If this could be handled in the build then maybe the `.txt` could be removed. Been a while since I looked at this so might have changed.

**Comment by clach04** [comment]
> IIRC we switched to md to benefit from markup, but then noticed that the txt is the one packaged into the installer via `ant jython-installer` (or so). Since the file is rarely changed we went for keeping them in sync manually so far. Have they gotten out of sync? That's unfortunate :(

They are quite different. @jamesmudd explanation makes sense, its likely for installer/build purposes. There are `@jython.version@` which look like template/variable markers.

My 2 cents, looks like they do serve different purposes so probably should be treated separately (assuming the installer still uses/needs it). What threw me off was the confusing duplicate names and slightly different file extensions, I probably wouldn't have been confused/opened a ticket if the .txt file was named .template (etc.).

**Comment by jeff5** [comment]
`README.txt` is processed into the text you see when installing Jython, here:
https://github.com/jython/jython/blob/5f29801fec49fdf0d17d880a7cb83983d3528411/build.xml#L637
It has been like that for a long time, except I tidied up the Ant target and fixed a few things to make sure it got accurate version information inside Ant automatically, as the original author clearly had intended.

`README.md` is a "new" addition for GitHub readers. IMO these have different readership and, rightly, different content. If it is confusing, we could change the name of README.txt, but it hadn't occurred to me it was.
