### ISSUE TITLE
Regression in 2.7.3 in `socket.socket.sendall` for sending Unicode

### ISSUE THREAD

**Issue by TheMatt2** [jython/jython#254]
# Description

In Jython 2.7.3, passing a unicode string to `socket.socket.sendall` causes a TypeError to be raised saying a memory buffer could not be created. This seems to have been introduced in https://github.com/jython/jython/commit/e7413a64db501995c68229ec7981bd21a928a004 when `sendall` was made to not be an alias for `send`.

https://github.com/jython/jython/blob/8d4ad5f222c94c4ad674131c38d26d7eaf7d5cd1/Lib/_socket.py#L1218-L1223

The subtle reason why this fails is Jython doesn't implicitly convert unicode to string for `sendall()`, while CPython 2 does.

Tested that sending unicode to `sendall` does work in Jython 2.7.1. Sending unicode to `sendall` also works in CPython 2.7.

# Steps to Reproduce

Run the following code in Jython 2.7.3 and observe the error.
A second Python process must also be created to communicate with it.

```
Jython 2.7.3 (tags/v2.7.3:5f29801fe, Sep 10 2022, 18:52:49)
[OpenJDK 64-Bit Server VM (Eclipse Adoptium)] on java20.0.1
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> listen_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> listen_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
>>> listen_socket.bind(('', 8888))
>>> listen_socket.listen(1)
>>> connection, address = listen_socket.accept()
>>> connection.sendall(u"hello\n")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/jython-standalone-2.7.3.jar/Lib/_socket$py.class", line 1459, in meth
  File "/path/to/jython-standalone-2.7.3.jar/Lib/_socket$py.class", line 0, in sendall
TypeError: cannot make memory view because object does not have the buffer interface
>>> 
```

Running the same code in Jython 2.7.1 works as expected:

```
Jython 2.7.1 (default:0df7adb1b397, Jun 30 2017, 19:02:43) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java1.8.0_181
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> listen_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> listen_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, True)
>>> listen_socket.bind(('', 8888))
>>> listen_socket.listen(1)
>>> connection, address = listen_socket.accept()
>>> connection.sendall(u"hello\n")
6
>>> 
```

Example code to run on another Python instance to connect to the port so the behavior can be seen.
Run the code above up to the `accept` line, then run this code in another process. Can be any version of Jython or Python for that matter.

```
Python 3.11.3 (main, Apr  7 2023, 19:29:16) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys, socket
>>> listen_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> listen_socket.connect(('', 8888))
>>> try:
...   stdout = sys.stdout.buffer # Python 3
... except AttributeError:
...   stdout = sys.stdout # Python 2
...
>>> while 1:
...   stdout.write(listen_socket.recv(1))
...   stdout.flush()
... 
```

## Notes

This seems to be the same issue as #211, but just manifesting directly in the socket library.

In that issue, there was a discussion about if the Python specification requires `sendall` and related commands
to accept unicode, since the [docs](https://docs.python.org/2.7/library/socket.html) only every refer to the argument as a "string", but there is no encoding flag. Hence, I agree the _better_ approach programmatically is to set an encoding explicitly.

_However_, Python 2 silently upgrades strings to unicode, and considers `unicode` to be a subclass of `basestring`.  Therefore, I suggest library like `socket` should quietly convert unicode to the network interface because Python does consider them to be (base)"strings". I also would like to point out this _is_ the behavior of Jython prior to the breaking change.

**Comment by TheMatt2** [comment]
Note from digging into this. I can not find anywhere in the Python [docs](https://docs.python.org/2/howto/unicode.html) that says sockets, or sys.stdout for that matter, will accept unicode.

_However_, the existence of the `sys.getdefaultencoding()` method does imply Python will try to implicitly convert unicode to a string using that encoding.

In CPython 2, _all_ built in functions that accept a string will implicitly convert unicode to string using the encoding from `sys.getdefaultencoding()`.

Link to the code in CPython 2 that ultimately converts unicode to string if a function asks for data of the `'s'` (string) type, as socket does.

https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Python/getargs.c#L851-L870

The hope would by Jython would comply with this behavior of how CPython behaves.

**Comment by jeff5** [comment]
> The subtle reason why this fails is Jython doesn't support `memoryview` for unicode, while CPython 2 does.

Not so (but it doesn't mean your PR is wrong). They respond the same way to `memoryview(u"hello")`. As you have found (second post) when CPython processes arguments to built-in functions those declared `s*` accept bytes-like objects *and Unicode* if it can be encoded as ascii.

`socket` has had quite a lot of Jython-specific modifications and `_socket` replaces a module in C. We have become fussier since 2.7.1 in ensuring `str` contains only bytes. It gives us greater conformity in many respects and in other places still bites unexpectedly.

**Comment by TheMatt2** [comment]
> They respond the same way to `memoryview(u"hello")`

Apologize, you are right. I meant to update the wording after my second post and clearly didn't.

Both CPython and Jython will give an error on passing unicode to `memoryview`

```
Python 2.7.17 (default, Dec 23 2019, 21:25:33) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> memoryview(u"hello")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: cannot make memory view because object does not have the buffer interface
```
It's not that Jython "doesn't support `memoryview`", just that CPython `socket` implicitly converts unicode to string

I updated the original post
