### ISSUE TITLE
`print` does not work as an expression in list comprehension

### ISSUE THREAD

**Issue by magicmq** [jython/jython#259]
Suppose I have the following example code:

```python
class UserMessage:

    def __init__(self, user, message):
        self.user = user
        self.message = message

    def __str__(self):
        return self.user + ': ' + self.message

messages = [UserMessage('User1', 'Message1'),
                     UserMessage('User2', 'Message2'),
                     UserMessage('User3', 'Message3'),
                     UserMessage('User4', 'Message4'),]

[print(user_message) for user_message in messages]
```

I would like to print each element of `messages` using list comprehension. However, I get the following error: `SyntaxError: no viable alternative at input 'print' (test.py, line 15)`. But, when I change the code to this:

```python
class UserMessage:

    def __init__(self, user, message):
        self.user = user
        self.message = message

    def __str__(self):
        return self.user + ': ' + self.message

messages = [UserMessage('User1', 'Message1'),
                     UserMessage('User2', 'Message2'),
                     UserMessage('User3', 'Message3'),
                     UserMessage('User4', 'Message4'),]

def print_user_message(user_message):
    print(user_message)

[print_user_message(user_message) for user_message in messages]
```

It works as intended. Is this expected behavior? I understand this may not be the intended use of list comprehension, but I should be able to use `print` as an expression in list comprehension (mainly for debugging), as it works correctly when tested outside of Jython (tested [here](https://www.online-python.com/)).

**Comment by jeff5** [comment]
`print` is a keyword in Python 2, not a function.
