### ISSUE TITLE
Guard against DLL hijacking

### ISSUE THREAD

**Issue by jeff5** [jython/jython#265]
Counterpart of https://github.com/NationalSecurityAgency/ghidra/issues/5306.

**Comment by jeff5** [comment]
This problem falls into two parts:
1. `jffi-1.2.dll`, and
2. everything else (including `crypt.dll`) needed by the `posix` module..

`jffi-1.2.dll` is found and loaded by `com.kenai.jffi.internal.StubLoader` along paths defined by the properties `jffi.boot.library.path` then `java.library.path`. These might be manipulable, but the latter clearly does not just affect JFFI. Finally (as is the case in tests) it extracts a copy from the JAR under a salted name. The logic is defined here: https://github.com/jnr/jffi/blob/70823a2404d78b1e2f90572d49956b21309df3c6/src/main/java/com/kenai/jffi/internal/StubLoader.java#L291-L302.

Everything else (the `posix` module is first to the trough) comes through a `jnr.ffi.LibraryLoader`. When it looks for DLLs it uses a potentially long list of directories decided by a static initialisation here: https://github.com/jnr/jnr-ffi/blob/2a422700759ef0dbb20b86888fa8b2c58e1b628a/src/main/java/jnr/ffi/LibraryLoader.java#L502-L507. It appears that defining `jnr.ffi.library.path` places us first on that path.

The common design feature to both is that we can define a place to look first, but we cannot (I think) prevent it looking in all the others, particularly along `java.library.path`, which we might want to preserve for other reasons. There are options here for mitigation of the risk by controlling these if it does no harm to the specific application.

**Comment by jeff5** [comment]
@ryanmkurtz and @RashidKhanPathan: do you think that defining trusted DLL locations in `jffi.boot.library.path` and `jnr.ffi.library.path` would be a satisfactory mitigation? Jython would look in a somewhat less controllable list of places if those libraries were not found where expected.

To address the root cause, we have to turn upstream to the JNR project and its libraries.

**Comment by RashidKhanPathan** [comment]
Yes Definately, defining trusted DLL Locations would be satisfactory mitigation for this, also using fully qualified paths when loading DLLs can also prevent Windows from searching for DLLs in unexpected locations as well as,

Another important practice that can help prevent DLL hijacking is to use access controls on the directories where DLL files are stored. This can help ensure that only authorized users are able to read or write to these directories, and can prevent an attacker from placing a malicious DLL in a directory where it can be loaded by a vulnerable program

**Comment by jeff5** [comment]
@RashidKhanPathan: my question was whether making Jython look in safe locations **first** would be satisfactory, if it still looks in the current unsafe ones afterwards. It seemed a bit weak.

As you probably know, the JVM looks along `java.library.path` which is derived from `PATH` on Windows. I would be reluctant to alter `PATH` or force `java.library.path` because others may be relying on the unmodified values. Both are under the control of the user or application.

Of interest: https://github.com/jnr/jffi/issues/47 (Disable loading of jffi-1.2.dll from current directory). Unresolved AFAICT.

**Comment by jeff5** [comment]
Notes from more digging. With the debugger I can see JFFI looking for:

- `jffi-1.2` checks for a definition of `jffi.boot.library.path`, then tries for "jffi-1.2.dll" along `java.library.path`, then (successfully) extracts the DLL from the JAR to `TEMP`.
- `msvcrt` tries the system-defined `dlopen()` first which succeeds.
- `kernel32` tries the system-defined `dlopen()` first which succeeds.
- `libcrypt.so.1` tries the system-defined `dlopen()`, then looks for a file called "libcrypt.so.1.dll" (bug?) along a composite path from `jnr.ffi`, then tries the system-defined `dlopen()` again with "libcrypt.so.1.dll".
- `crypt` tries the system-defined `dlopen()`, then looks for a file called "crypt.dll" along a composite path from `jnr.ffi`, then tries the system-defined `dlopen()` again with "crypt.dll".

The composite path from `jnr.ffi` is the concatenation of the properties "jnr.ffi.library.path", "jaffl.library.path", "jna.library.path" and "java.library.path".

If `jffi-1.2` were in a safe location we could place on `jffi.boot.library.path`, that would take precedence, although if it were ever missing from there, nothing will prevent the default search of `java.library.path`. I'm not sure where '.' gets added to that in Jython. In the test it was not on my `PATH`.

For every other DLL, JFFI tries the system-defined `dlopen()` which I believe uses the algorithm here: https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order (for unpackaged apps). That is a lot of places and includes the current folder, if the search is not configured with `SetDllDirectory`.

All of this logic is within JFFI. We just create a module dependent on it. The properties Jython can manipulate are equally available to the application that uses Jython.

I'll look where '.' gets added to `PATH`.

**Comment by jeff5** [comment]
> I'll look where '.' gets added to `PATH`.

This is the wrong question. `PATH` is not manipulated at all, but "." is added when the JVM forms `java.library.path`. That happens here:
https://github.com/openjdk/jdk/blob/58f5826ff48c20446a0c2ea44da107867126f638/src/hotspot/os/windows/os_windows.cpp#L338-L382

It only happens if `java.library.path` is not defined (on the `java` command, say).

**Comment by jeff5** [comment]
The original worry was that Jython looks in "." for named DLLs `jffi-1.2`, `libcrypt.so.1` and `crypt`. (Poor control of other places on that path may be a worry too.) Investigation shows that all of the behaviour behind these searches is defined within `jnr-jffi` and `jnr-posix`.

The only ways I found to influence where Jython looks are:

1. Define `java.library.path` before the JVM does, to exclude "." and any other place we can't trust. (This affects all DLLs, but those other than `jffi-1.2` will still be sought with Windows `LoadLibrary`.)
2. Define `jffi.boot.library.path` and put jffi-1.2.dll on it. (This only affects `jffi-1.2`.)
3. Place a copy of `libcrypt.so.1.dll` where JFFI will find it before trying other places.

None of these reliably solves the problem. And they have down-sides: 1. disables an expected behaviour of the JVM; 2. complicates installation; and so would 3. if we had the weirdly-named DLL. 

I'm forced to conclude that the root cause lies with JVM and Windows behaviour, and there isn't a silver bullet Jython can supply. Solutions will be specific: to tailor `java.library.path` to reflect particular application needs and possibly configure the run-time environment to make DLL search relatively safe.

JNR could mitigate the problem a little if they offered options not to throw quite so many places at the search, but JNR is only following the JVM's and Windows' definitions.
