### ISSUE TITLE
Jython 2.7.2 not calling the right overloaded java method for boolean

### ISSUE THREAD

**Issue by yogi1967** [jython/jython#276]
I'm using 3rd party jar file which defines:

public class StreamTable extends HashMap {etc}
it defines:

   public final void put(Object key, Object value)
   **public final void put(String key, boolean value)
   public final void put(Object key, boolean value)
   public final void put(Object key, String value)
   public Object put(String key, Object value)
   public final void put(Object key, long value)
   public final void put(String key, long value)
   public final void put(String key, String value)
   public final void put(Object key, int value) 
   public final void put(String key, int value)
 etc

My Jython:
key="a"
value=True
if I call the object using .put(key, value) then it's not calling the .put(String key, boolean value) method. I'm fairly sure it's calling the .put(Object key, Object value) method (or one of the others).

However if I call .put(key, Boolean(value)) then it does call the right boolean method.

Is this a bug?

**Comment by yogi1967** [comment]
... perhaps it's calling the int method.... how does it determine which to call..?

**Comment by pjs726** [comment]
Would it be possible for you to share the jar file or source code? If not, I suppose I could try to recreate the code as you describe it, but there's no guarantee the behavior will be the same.

Also I see you're not sure which method exactly is being called. Would it be possible for you to modify the StreamTable code to give some debug information about which method was called? Something like this:

```
public final void put(Object key, Object value) {
     System.err.println("Object key, Object value");
     ....
}

public final void put(String key, boolean value) {
     System.err.println("String key, boolean value");
     ....
}

....
```

That way we could know for sure which method is being called.

**Comment by yogi1967** [comment]
It's a third-party class and I do not have a java environment to play with.. Here is the decompiled .java file (redacted down to just the methods in question). Hope this is enough... Let me know? Thanks


```
package com.xxx.XXX;

import java.io.Closeable;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.io.PrintStream;
import java.io.Reader;
import java.io.Serializable;
import java.io.StringReader;
import java.io.StringWriter;
import java.io.Writer;
import java.net.URL;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

public class StreamTable extends HashMap<String, Object> {
   public StreamTable() {
   }

   public final Object get(String key, Object defaultVal) {
      Object var10000 = super.get(key);
      return var10000 == null ? defaultVal : var10000;
   }

   public String toString() {
      String var10000 = this.writeToString();
      return var10000;
   }

   public final int getInt(String key, int defaultVal) {
      try {
         return Integer.parseInt(String.valueOf(this.get((Object)key)));
      } catch (Exception var4) {
         return defaultVal;
      }
   }

   public final int getInt(Object key, int defaultVal) {
      return this.getInt(key.toString(), defaultVal);
   }

   public final long getLong(String key, long defaultVal) {
      try {
         return Long.parseLong(String.valueOf(this.get((Object)key)));
      } catch (Exception var5) {
         return defaultVal;
      }
   }

   public final boolean getBoolean(Object key, boolean defaultVal) {
      String var10000 = this.getStr((String)key.toString(), (String)null);
      if (var10000 == null) {
         return defaultVal;
      } else {
         String result = var10000;
         result = StringsKt.trimStart((CharSequence)result).toString();
         if (result.length() <= 0) {
            return defaultVal;
         } else {
            char var4 = result.charAt(0);
            if ((((var4 == '1' ? true : var4 == 'y') ? true : var4 == 't') ? true : var4 == 'Y') ? true : var4 == 'T') {
               return true;
            } else {
               return ((((var4 == '0' ? true : var4 == 'n') ? true : var4 == 'f') ? true : var4 == 'N') ? true : var4 == 'F') ? false : defaultVal;
            }
         }
      }
   }

   public final String getStr(String key, String defaultVal) {
      Object var10000 = this.get((Object)key);
      if (var10000 == null) {
         return defaultVal;
      } else {
         Object value = var10000;
         return value.toString();
      }
   }

   public String getStr(Object key, String defaultVal) {
      Object value = ((Map)this).get(key);
      String var10000;
      if (value != null) {
         var10000 = value.toString();
         if (var10000 != null) {
            return var10000;
         }
      }

      var10000 = defaultVal;
      return var10000;
   }

   public final String getString(String key, String defaultVal) {
      return this.getStr(key, defaultVal);
   }

   public final String[] getStrList(Object key) {
      return this.getStrList(key.toString());
   }

   public final String[] getStrList(String key) {
      try {
         StreamVector var10000 = (StreamVector)this.get((Object)key);
         if (var10000 == null) {
            return new String[0];
         } else {
            StreamVector sv = var10000;
            int var3 = 0;
            int var4 = sv.size();

            String[] var5;
            for(var5 = new String[var4]; var3 < var4; ++var3) {
               var5[var3] = String.valueOf(sv.get(var3));
            }

            return var5;
         }
      } catch (Exception var7) {
         return new String[0];
      }
   }

   public final void put(Object key, Object value) {
      this.put(key.toString(), value);
   }

   public final void put(Object key, String value) {
      this.put(key.toString(), value);
   }

   public Object put(String key, Object value) {
      return value == null ? super.remove(key) : super.put(key, value);
   }

   public final void put(Object key, long value) {
      this.put(key.toString(), value);
   }

   public final void put(String key, long value) {
      super.put(key, String.valueOf(value));
   }

   public final void put(Object key, boolean value) {
      this.put(key.toString(), value);
   }

   public final void put(String key, boolean value) {
      super.put(key, value ? "Y" : "N");
   }

   public final void put(String key, String value) {
      if (value == null) {
         super.remove(key);
      } else {
         super.put(key, value);
      }

   }

   public final void put(Object key, int value) {
      this.put(key.toString(), value);
   }

   public final void put(String key, int value) {
      super.put(key, String.valueOf(value));
   }

   public final void put(String key, URL value) {
      if (value == null) {
         super.remove(key);
      } else {
         super.put(key, value.toString());
      }

   }

}

```

**Comment by yogi1967** [comment]
PS - The point of this class is to store objects as strings to be saved to disk (preferences). So in this instance a Boolean should become "Y" or "N", but it's becoming "0" or "1". This does suggest it's being treated as an int

**Comment by jeff5** [comment]
> ... perhaps it's calling the int method.... how does it determine which to call..?

It tries to find the most specific match to the argument types. Python `True` is a `PyBoolean`. While it can be coerced to a Java `boolean` it can equally well be coerced to `Object`. Not sure about order.

A complication may be that classes implementing containers (`Map`, `List,`) etc. get some special treatment to make them look like  Python equivalents. This may end up favouring the API methods (`Map.put` in this case).

@pjs726 : thanks for considering investigating this. I think a synthetic example would probably be preferable for debugging and could be added to the Java tests.

**Comment by yogi1967** [comment]
How can I find out the order - or where to look for myself..? Thanks

**Comment by jeff5** [comment]
Look for classes with the word "Reflected" in their name, especially `ReflectedFunction `and `ReflectedArgs`.

Documentation is thin on the ground, sorry.

**Comment by yogi1967** [comment]
@pjs726 - Did you manage to investigate this?

I wonder if this is the code?
org.python.core.ReflectedArgs.precedence(Class) : int
```
  public static int precedence(Class<?> arg) {
    if (arg == Object.class)
      return 3000; 
    if (arg.isPrimitive()) {
      if (arg == long.class)
        return 10; 
      if (arg == int.class)
        return 11; 
      if (arg == short.class)
        return 12; 
      if (arg == char.class)
        return 13; 
      if (arg == byte.class)
        return 14; 
      if (arg == double.class)
        return 20; 
      if (arg == float.class)
        return 21; 
      if (arg == boolean.class)
        return 30; 
    } 
    if (arg == String.class)
      return 40; 
    if (arg.isArray()) {
      Class<?> componentType = arg.getComponentType();
      if (componentType == Object.class)
        return 2500; 
      return 100 + precedence(componentType);
    } 
    return 2000;
  }
```

**Comment by yogi1967** [comment]
I had another one today. This the java:

```
    public DateRange(@Nullable Date start, @Nullable Date end) {
        this.startDateInt = DateUtil.convertDateToInt(start);
        this.endDateInt = DateUtil.convertDateToInt(end);
        this.calcNumDays();
    }

    public DateRange(int start, int end) {
        this.startDateInt = start;
        this.endDateInt = end;
        this.calcNumDays();
    }

    public DateRange(long start, long end) {
        this(new Date(start), new Date(end));
    }


```

Calling this with Jython int's causes the constructor with long parameters to be selected (not the int's). To call the right constructor, I have to call it with java.lang.Integer(value)'s.

**Comment by jeff5** [comment]
I think the `long`/`int` problem *is* explained by the precedence code:
```
      if (arg == long.class)
        return 10; 
      if (arg == int.class)
        return 11; 
```
This looks to me like it favours (Java) `long` over (Java) `int` when ordering overloaded method definitions to try. And for each signature it will try to convert the actual (Python) `int` argument to match the formal argument, which will work first with `long`.

It *may* explain the `long`/`boolean` problem too. 

I think this is incorrect behaviour but it would take a lot of changes to fix it (and everything that would probably break as a result).

**Comment by yogi1967** [comment]
😔 Thanks for the explanation.
[Edited: removed quoted e-mail]

**Comment by robertpatrick** [comment]
@jeff5 Using the branch from PR #282 and the example method definitions and `key = 'a'` and `value = True`, I get this:

```
Invoked put(String key, long value)
```

If I comment out that method and rerun the test, I get:

```
Invoked put(String key, int value)
```

If I comment out that method and rerun the test, I get:

```
Invoked put(String key, boolean value)
```

This whole static precedence assignment code for "number-like" types seems problematic and likely has never really worked correctly.  For example, if I change the precedence of `boolean` to be higher than `long`, if I call `put('a', 1L)`, it matches the `put(String key, boolean value)` method.   I'm not sure how you fix this without revisiting the whole static precedence strategy.

**Comment by jeff5** [comment]
> I'm not sure how you fix this without revisiting the whole static precedence strategy.

It is arguably not broken, because that's what Jython has done for 25 years and there is no spec. I'd prefer it to be closer to Java, but I'm loath to change this behaviour in Jython 2.

As @yogi1967 points out, you can (more or less) call the specific definition by constructing instances of the right types explicitly. I was sceptical about this as I know that method returns get coerced to a Python type, but I've traced some examples and it is different for constructors.

I'll add a little demonstration to the tests to remind us.

**Comment by yogi1967** [comment]
@jeff5. Yes I have proven this. With Java constructors of first (int) and then second (long). When calling with Class(int) it gets the (wrong) long constructor, but calling with Class(Integer(int)) gets the right constructor. So when called with Integer() it cannot be converting and must be passing the class along. 

This leads me to a question, please. 

If you call a Java Class with a Class/Type then I assume/presume that Jython NEVER converts the arguments to Python types. Is this correct? Ie the actual class/type is passed? I presume conversions only occur when passing a Python primitive and it attempts to convert it to a Java primitive. Is this correct? 

Hence, this must be why calling a Class with an implicit Java TYPE for the primitive works? I presume this would also work by calling with Boolean(), Integer(), Long() instead of passing bool, int, ? (ah ha). 

Thanks.

**Comment by jeff5** [comment]
> If you call a Java Class with a Class/Type then I assume/presume that Jython NEVER converts the arguments to Python types.

The terms of the question are a bit confusing, but I think the answer is in this account:

* Built-in types like `int` are "crafted" implementations extending `PyObject` that provide implementations of the methods and the operations those types should have in Python.
* Objects of a "found" Java class (meaning not one written explicitly to be a Python object) are handled via a proxy object that extends `PyObject`, but the proxy passes method calls etc. to the object it proxies. So you don't "see" the proxy object in your code: it seems to be a Java object.
* When we call a method from a "found" Java class, all the arguments are therefore some kind of `PyObject`. We try to fit the value to the type required in the signature. A "crafted" object (passed as an argument) may implement conversions of its value to the requested type. A proxy (passed as an argument) will ask whether its proxied object is of the requested type, including treating a request for a Java primitive as equivalent to requesting the boxed type.
* Almost any Python expression, including function return values, will be an instance of a "crafted" type, so if you write `1L` or even `Long.valueOf(1)` you will get a Python `long` (a `PyLong`) not an object proxying a Java `Long`.
* The exception is for constructors, which cause a proxy to be created (in `__new__`), then call the Java constructor as if it were `__init__` to dangle an instance of that Java type from the proxy. If this is done sufficiently close[1] to the call that consumes it, then argument processing will deliver the proxied object to the Java argument.

For an overloaded method, requesting types in a signature, but finding no conversion in some cases, is what drives the selection of an implementation. The search order is decided by the precedence of types noted above. I added some test material in #290 to explore/pin this behaviour.

[1] I haven't tested what sufficiently close would be: probably storing in a local variable and retrieving is ok. I'm not sure about a global (because it is in a `PyDictionary`). Any arithmetic will give you a "crafted" object as the result.

**Comment by jeff5** [comment]
I'll close this as I think that what can be improved in Jython 2 has been covered in #282 and #290.
