### ISSUE TITLE
Argument coercion fails for Java interface with default methods

### ISSUE THREAD

**Issue by pturmel** [jython/jython#277]
Same for bound methods.

When checking for suitability (@ PyFunction.java:512 and PyMethod.java:376 as of today) for coercion, the number of methods is check without accounting for default methods.  Affects interfaces like `java.util.function.Consumer<?>` and `java.util.function.BiConsumer<?,?>` where modern java includes a default `.andThen()` method.

It seems to me a simple:
```
	if (method.isDefault()) continue;
```
in the alternate check's loop (ahead of `if (name == null ||...` in each) would let the proxy be created.

The `.invoke()` method of each would then need to pass through calls to default methods, something like:
```
	if (method.getDeclaringClass() == Object.class || method.isDefault()) {
		return method.invoke( this, args );
	} else ...
```

If this seems like a reasonable approach, I'll generate a PR.

**Comment by jeff5** [comment]
It's a known gap we've never done the analysis to fill in. Thanks, I'll look at the PR.

**Comment by pturmel** [comment]
I didn't see any gotchas elsewhere in the codebase, and this change introduced no new regressions in the test suite (a socket regression was there before and after the commit).  It'll definitely allow me to clean up some code that currently generates full jython classes implementing such interfaces.  Some long-standing work-arounds that annoyed me this past week. (:
