### ISSUE TITLE
May I Ask?

### ISSUE THREAD

**Issue by Tax0787** [jython/jython#279]
I'm Korean middle school students.
Nomal middle school students
And I want to be Programmer
And I have a big plan.
So I'll use it but...
I'm Korean
As you know, I need to study 4 years that 365 * 4 days, 24 * 365 * 4 days
and It difficult to programming for secret
But If I am be adult, then I'll programming a lot
Maybe Programming world is changed
But I'll use this repository
Please keep save this repository

My Big Dream, the plan what I called Project Beryllium is
The Reason thet I'm still alive never die my self

So keep my dream please...

If you want save my life.

Thanks for reading

**Comment by Wamadahama** [comment]
Tell me more about Project Beryllium

**Comment by jeff5** [comment]
Glad you find it useful. We do intend to keep developing Jython towards a modern Python 3.

Best wishes for your studies. (Remember to balance them with other interests and sleep.)

> Tell me more about Project Beryllium

Maybe look on @Tax0787's pages. As this isn't really an issue, I'll close it here.

**Comment by Tax0787** [comment]
Thanks for support my future
