### ISSUE TITLE
LineNumberTable deprecated for removal in 2.6 still there

### ISSUE THREAD

**Issue by Stewori** [jython/jython#280]
I just randomly noticed that org.python.compiler.LineNumberTable contains the deprecation note:
"Not used. Delete in 2.6."

If it is still in use, the note should be removed, otherwise the class. This is not high priority, this issue is opened mainly as a reminder.

**Comment by jeff5** [comment]
Eclipse, which is quite good at finding uses, tells me it isn't used in Jython. It is public, like too much, but anyone consuming it has a had a fair few years warning.
