### ISSUE TITLE
Jython 2.7.3 invoking the wrong overloaded Java constructor

### ISSUE THREAD

**Issue by robertpatrick** [jython/jython#281]
Our project ([WebLogic Deploy Tooling](https://github.com)) has code that is working properly on Jython 2.7.1.  Our upcoming release has moved to Jython 2.7.3 and the code that was previously working is now failing.  Here is a simplified snippet of what we are doing (with some debugging lines added):

```python
import java.lang.Throwable as Throwable
import oracle.weblogic.deploy.create.CreateException as CreateException

...

def create_create_exception(key, *args, **kwargs):
    """
    Create a CreateException from a message id, list of message parameters and Throwable error.
    :param key: key to the message in resource bundler or the message itself
    :param args: list of parameters for the parameters or empty if none needed for the message
    :param kwargs: contains Throwable or instance if present
    :return: CreateException encapsulating the exception information
    """
    arg_list, error = _return_exception_params(*args, **kwargs)
    print('arg_list (%s) = %s' % (type(arg_list), arg_list))

    arg_len = len(arg_list)
    if error is not None:
        if isinstance(error, Throwable) is False:
            print('error is not Throwable')
            error = convert_error_to_exception()
            print('converted error = %s' % error)
        if arg_len > 0:
            print('Calling CreateException(key, error, arg_list) with error that is an instance of Throwable (%s)' % isinstance(error, Throwable))
            ex = CreateException(key, error, arg_list)
        else:
            print('Calling CreateException(key, error)')
            ex = CreateException(key, error)
    else:
        if arg_len > 0:
            print('Calling CreateException(key, arg_list)')
            ex = CreateException(key, arg_list)
        else:
            print('Calling CreateException(key)')
            ex = CreateException(key)
    return ex
```

The CreateException class has 5 overloaded constructor methods including the two relevant to this situation:

```java
public class CreateException extends BundleAwareException {
    private static final long serialVersionUID = 1L;

    public CreateException() {
        // default constructor
    }

    public CreateException(String messageID) {
        super(messageID);
    }

    public CreateException(String messageID, Object... params) {
        super(messageID, params);
        System.out.println("Inside CreateException(String messageID, Object... params) constructor");
        if (params[0] instanceof Throwable) {
            System.out.println("Inside wrong CreateException() constructor");
        } else {
            System.out.println("Second arg is not a Throwable: " + params[0].getClass().getName());
        }
    }

    public CreateException(String messageID, Throwable cause) {
        super(messageID, cause);
    }

    public CreateException(String messageID, Throwable cause, Object... params) {
        super(messageID, cause, params);
        System.out.println("Inside CreateException(String messageID, Throwable cause, Object... params) constructor");
    }

    public CreateException(Throwable cause) {
        super(cause);
    }

    @Override
    public String getBundleName() {
        return ExceptionHelper.getResourceBundleName();
    }
}
```

When running the code with Jython 2.7.1, the output from the debugging code look like this:

```
arg_list (<type 'list'>) = ['Password', u'/Security/mydomain/User/weblogic', '<masked>', u'60455: Invalid password.\n60455: The password must be at least 8 alphanumeric characters with at least one number or special character.\n60455: Correct the password.']
Calling CreateException(key, error, arg_list) with error that is an instance of Throwable (True)
Inside CreateException(String messageID, Throwable cause, Object... params) constructor
```

When switching to 2.7.3, the output changes to reflect the problem:

```
arg_list (<type 'list'>) = ['Password', u'/Security/mydomain/User/weblogic', '<masked>', u'60455: Invalid password.\n60455: The password must be at least 8 alphaumeric characters with at least one number or special character.\n60455: Correct the password.']
Calling CreateException(key, error, arg_list) with error that is an instance of Throwable (True)
Inside CreateException(String messageID, Object... params) constructor
Inside wrong CreateException() constructor
```

**Comment by robertpatrick** [comment]
This seems to be similar to #276

**Comment by robertpatrick** [comment]
@jeff5 I understand the cause of the problem now but looking for some input on how you would suggest that we fix this...

The problem is that in the PyReflectedConstructor's `__call__` method, the code iterates through the arg lists for each constructor and finds the first "match" and stops looking:

```java
           // Just look for a constructor with no keyword args
           int n = nargs;
           for (int i = 0; i < n; i++) {
               rargs = argslist[i];
               if (rargs.matches(null, args, Py.NoKeywords, callData)) {
                   method = rargs.method;
                   break;
               }
           }
```

The problem is that with varargs in the mix, there can be more than one match and some matches are better than others.  For example (omitting constructor bodies for clarity):

```java
public class MyClass {
    public MyClass(String key) {}
    public MyClass(String key, Object... params) {}
    public MyClass(String key, Throwable error, Object... params) {}
    public MyClass(String key, Throwable error) {}
}
```

Now when I create an instance of MyClass, as shown below, both the second and third constructors will pass the `match()` test but the third constructor match is "better" (and what gets called when creating the object from pure Java with the same args). 

```python
from java.lang import Exception
import MyClass

error = Exception("oops")
myclass = MyClass("foo", error, "arg1", "arg2")
```

It gets even trickier when you call `myclass = MyClass("foo", error)` since this call matches both constructors 2 and 4 but 4 is a "better" match and should be the one selected.

What I don't understand is that this works perfectly in Jython 2.7.1 but not in 2.7.3 (or master).  I have been looking for the change that broke this but have yet to find it.  Before I create a fix, it would be good to get input from the maintainer(s) on how best to fix this (instead of me dreaming up my own way, which is likely to be more complex than necessary).

**Comment by robertpatrick** [comment]
I have narrowed down timeframe when this code was broken.  Jython at tag `v2.7.3b1` works fine and is broken at tag `v2.7.3rc1`.

**Comment by robertpatrick** [comment]
PR #201, as simple as it seems, broke this.

**Comment by jeff5** [comment]
@robertpatrick Thanks so much for investigating this as energetically as you have. If I recall correctly, Jython tries to establish an order such that the first match is the one Java would choose. @tpoliaw, who has done most in this area recently, has noticed that #201 is not quite correct and had a PR in the wings ... .

I sense a really thorough set of tests is needed.

**Comment by robertpatrick** [comment]
@jeff5 as a workaround, I have reverted #201.  I think the code that ensures boxing of the actual arguments when `isVarArgs` is true is causing a premature match where otherwise, it does the right thing by looking at the non-varargs matching arguments, as is, which does choose the right method.

**Comment by tpoliaw** [comment]
> PR #201, as simple as it seems, broke this.

Yeah, sorry about that, as  I mentioned in the PR, we got caught out by it as well. I still think that PR is correct, it just exposed a different bug elsewhere. Even in 2.7.1, the same issue can be seen in non-constructors as in #221.

I am trying to dig out the WIP fix I had from when I opened that issue but it was a year and a new computer ago so it might take a moment or several.

**Comment by yogi1967** [comment]
I had another one today. This the java:

```
    public DateRange(@Nullable Date start, @Nullable Date end) {
        this.startDateInt = DateUtil.convertDateToInt(start);
        this.endDateInt = DateUtil.convertDateToInt(end);
        this.calcNumDays();
    }

    public DateRange(int start, int end) {
        this.startDateInt = start;
        this.endDateInt = end;
        this.calcNumDays();
    }

    public DateRange(long start, long end) {
        this(new Date(start), new Date(end));
    }


```

Calling this with Jython int's causes the constructor with long parameters to be selected (not the int's). To call the right constructor, I have to call it with java.lang.Integer(value)'s.

**Comment by jeff5** [comment]
> I had another one today. This the java:
> ...
> 
> Calling this with Jython int's causes the constructor with long parameters to be selected (not the int's). To call the right constructor, I have to call it with java.lang.Integer(value)'s.

That's awful. How would one deal with that in Python 3, with only one kind of `int`? It makes me think that in hard cases, one must be able to say exactly which method is wanted.

**Comment by robertpatrick** [comment]
> I had another one today. This the java:
> 
> ```
>     public DateRange(@Nullable Date start, @Nullable Date end) {
>         this.startDateInt = DateUtil.convertDateToInt(start);
>         this.endDateInt = DateUtil.convertDateToInt(end);
>         this.calcNumDays();
>     }
> 
>     public DateRange(int start, int end) {
>         this.startDateInt = start;
>         this.endDateInt = end;
>         this.calcNumDays();
>     }
> 
>     public DateRange(long start, long end) {
>         this(new Date(start), new Date(end));
>     }
> ```
> 
> Calling this with Jython int's causes the constructor with long parameters to be selected (not the int's). To call the right constructor, I have to call it with java.lang.Integer(value)'s.

As I said in the other thread:

1. This behavior hasn’t changed since at least Jython 2.2.1 so changing the behavior would definitely be backwards incompatible.
2. This conversion happens way before the method matching code is invoked.  By the time it gets there, Jython has already converted the type to a long.  As such, the method matching code is doing the right thing.

**Comment by jeff5** [comment]
> I had another one today. This the java:

@yogi1967 : do you agree this is a case of #276, while @robertpatrick's is specifically a problem with variable-arity signatures?

**Comment by jeff5** [comment]
@robertpatrick : I believe this one is solved in #282. Ok?

I wish I'd added a test more like your case in that PR, but when I do, it passes.

**Comment by yogi1967** [comment]
@jeff5 I would agree that my "I had another one today. This the java:" is the same issue as #282

**Comment by jeff5** [comment]
> @jeff5 I would agree that my "I had another one today. This the java:" is the same issue as #282

I argue it is #276, which is a "won't fix". The discussion provides a work-around when you understand the limitations.
