### ISSUE TITLE
Interactive interpreter awaits input instead of raising syntax error

### ISSUE THREAD

**Issue by ericmshort** [jython/jython#302]
In jython interactive mode
def testFoo(*args, **kwargs):
...     print('Inside testFoo')
... 
>>> 
>>> testFoo('arg1', 'arg2', servers='server1','server2')
... 

The runSource returns true and is expecting more input.  Version 2.2.1 gives a SyntaxError: non-keyword arg after keyword arg

**Comment by robertpatrick** [comment]
@jeff5 We have validated that in Jython 2.2.1, we are getting an exception from the InteractiveInterpreter, as we would expect:

```
wls:/offline> def testFoo(*args, **kwargs):
...    print('Inside testFoo')
...
wls:/offline> testFoo('arg1', 'arg2', servers='server1','server2')
Traceback (innermost last):
  (no code object) at line 0
  File "<console>", line 1
	testFoo('arg1', 'arg2', servers='server1','server2')
	                                          ^
SyntaxError: non-keyword argument following keyword
wls:/offline> 
```

where as with the master branch, the interpreter seems to be expecting additional input:

```
jython/bin/jython
Jython 2.7.4a1-SNAPSHOT (heads/master:148bf3749, Jan 30 2024, 15:47:30)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java17.0.9
Type "help", "copyright", "credits" or "license" for more information.
>>> def testFoo(*args, **kwargs):
...     print('Inside testFoo')
... 
>>> 
>>> testFoo('arg1', 'arg2', servers='server1','server2')
... 
```

**Comment by robertpatrick** [comment]
@jeff5 From a cursory investigation, it seems that the [validatePartialSentence() method](https://github.com/jython/jython/blob/master/src/org/python/core/ParserFacade.java#L232) is returning an incorrect response for this single line with a syntax error...

```
Jython 2.7.4a1-SNAPSHOT (heads/master-dirty:148bf3749, Feb 1 2024, 11:03:00)
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)] on java17.0.9
Type "help", "copyright", "credits" or "license" for more information.
>>> def testMe(*args, **kwargs):
partialParse throwable = org.python.antlr.ParseException
partialParse exception = org.python.core.PySyntaxError
validPartialSentence kind = single
validPartialSentence kind = single
validPartialSentence returning true
runsource compile succeeded
runsource compile code is None
push: runsource more = true
...     print('Inside testMe')
partialParse throwable = org.python.antlr.ParseException
partialParse exception = org.python.core.PySyntaxError
validPartialSentence kind = single
validPartialSentence kind = single
validPartialSentence returning true
runsource compile succeeded
runsource compile code is None
push: runsource more = true
... 
runsource compile succeeded
push: runsource more = false
>>> testMe('abc', 'def', servers='123','456')
partialParse throwable = org.python.antlr.ParseException
partialParse exception = org.python.core.PySyntaxError
validPartialSentence kind = single
validPartialSentence kind = single
validPartialSentence returning true
runsource compile succeeded
runsource compile code is None
push: runsource more = true
... 
```

**Comment by jeff5** [comment]
That's really useful, thanks. I have seen the REPL do this, but never pinned it down. (It's always when I'm more interested in something else.)

It seems like the syntax error is detected, but the REPL responds incorrectly with continuation lines where it should throw you back to the prompt.

**Comment by jeff5** [comment]
I'd say the problem is that the syntax error is detected from data gathered when constructing the AST as defined in the grammar here:
https://github.com/jython/jython/blob/148bf3749d9c12d55017bbd9556bb0529af6de35/grammar/Python.g#L2153-L2158
The Jython REPL has to figure out whether a syntax error is permanent or just due to an incomplete line, so it asks again for a parse by a different grammar, that treats partial lines as valid but doesn't generate an AST. The corresponding clause in that grammar does not detect the syntax error (because it wasn't gathering the necessary information):
https://github.com/jython/jython/blob/148bf3749d9c12d55017bbd9556bb0529af6de35/grammar/PythonPartial.g#L869-L876
Jython therefore acts as if everything will be ok once you finish your input. This goes on forever.

**Comment by jeff5** [comment]
There are multiple examples of errors that `Python.g` recognises and `PythonPartial.g` doesn't because they are acceptable to the grammar of Python as implemented. The problematic errors are (I think, so far) what are called "semantic errors". There is not a firm line between the two categories, and Python raises `SyntaxError` for both.

I tried adding some of the semantic error detection to `PythonPartial.g` but that is difficult because it depends on making  `PythonPartial.g` collect the same information as  `Python.g`, which it doesn't.

**Comment by robertpatrick** [comment]
@jeff5 I guess something changed between 2.2.1 and the present that caused this to no longer work properly.  Did `PythonPartial.g` not exist in 2.2.1?

**Comment by jeff5** [comment]
> Did `PythonPartial.g` not exist in 2.2.1?

Starts with 2.5 https://github.com/jython/jython/commit/a8b0023405fee35527cb3f700fddb9eca8a7a652

The exception raised by `Python.g` is examined in `fixParseError`:
https://github.com/jython/jython/blob/148bf3749d9c12d55017bbd9556bb0529af6de35/src/org/python/core/ParserFacade.java#L70
which is really where the assumption is made that a `ParseException` will either be found wrong again in `PythonPartial.g`, or will be ok if we just wait for more input. Unfortunately, this is not true of semantic errors `PythonPartial.g` doesn't detect.

I tried making `PythonPartial.g` detect them, but it got messy fast. Plan B is to have `Python.g` distinguish the recoverability of exceptions when it generates them.

**Comment by jeff5** [comment]
Plan B is looking good. Previously these were all problematic and on my local repo are no longer:
```
>>> foo(a=1, b)
  File "<stdin>", line 1
    foo(a=1, b)
            ^
SyntaxError: non-keyword arg after keyword arg
>>> bar(a=1, b=2, a=3)
  File "<stdin>", line 1
    bar(a=1, b=2, a=3)
                 ^
SyntaxError: keyword arguments repeated
>>> bar(*a, b)
  File "<stdin>", line 1
    bar(*a, b)
           ^
SyntaxError: only named arguments may follow *expression
>>> def foo(bar=1, baz=2, qux):
  File "<stdin>", line 1
    def foo(bar=1, baz=2, qux):
                         ^
SyntaxError: non-default argument follows default argument
>>> try:
...     pass
... finally:
...     continue
  File "<stdin>", line 4
    continue
    ^
SyntaxError: 'continue' not supported inside 'finally' clause
```
Just testing and I'll make a PR. Not sure I've got absolutely everything.

**Comment by robertpatrick** [comment]
@jeff5 Any ETA on a Jython 2.7.4 release?

**Comment by jeff5** [comment]
When that green bar gets to the right hand-end. If I sufficiently resist the temptation to add more issues, there could be a beta by the weekend.

**Comment by Stewori** [comment]
I am going to apply some documentation-only changes I wish to go into 2.7.4. Likely won't make it until weekend, but since it's doc-only I claim it is okay to do it during beta phase.

**Comment by jeff5** [comment]
> @jeff5 Any ETA on a Jython 2.7.4 release?

While I've resisted the temptation of further issues, mostly, I've encountered a bug in `sys.exit()` on Java 11 during regression tests. It puts things back a couple or three weeks (due to other commitments).
