### ISSUE TITLE
from java import * not working in Java 21

### ISSUE THREAD

**Issue by benken-parasoft** [jython/jython#304]
[Issue 105](https://github.com/jython/jython/issues/105) is happening again but this time in Java 21.

This works in Java 17 but not Java 21:
```
from java.util import *
d = Date()
```

In Java 21, this results in:
```
NameError: global name 'Date' is not defined
```

In Java 21, I have to use "from java.util import Date" instead of "from java.util import *".
This problem happens with "import *" from other "java" packages as well, not just "java.util".

**Comment by benken-parasoft** [comment]
I notice the build.xml references ASM 9.3 which supports Java 19.
I expect ASM would have to be updated to at least 9.5 to support Java 21.

**Comment by benken-parasoft** [comment]
It would be nice if Jython pushed out regular service releases for third party library updates to stay ahead of re-occurring issues like this as well as CVEs like the one in Guava ([issue 269](https://github.com/jython/jython/issues/269)).

**Comment by jeff5** [comment]
> I notice the build.xml references ASM 9.3 which supports Java 19. I expect ASM would have to be updated to at least 9.5 to support Java 21.

I'll see if it's that simple.

**Comment by jeff5** [comment]
> I'll see if it's that simple.

It is. Thanks for suggesting.
