### ISSUE TITLE
Unable to execute custom package commands like cloudpickle using PythonInterpreter.exec (or eval())

### ISSUE THREAD

**Issue by tvpadmanabhan** [jython/jython#318]
Hi all,
    I try to do the following:

```
java -jar ~/.m2/repository/org/python/jython-standalone/2.7.3/jython-standalone-2.7.3.jar -m pip install cloudpickle
java -cp myapp.jar -Dparams mymainclass arguments
```

The problem is that inside the main class when I invoke like this:

```
PythonInterpreter pythonInterpreter = nes PythonInterpreter();
pythoninterpreter.exec("cloudpickle <some byte_string>") 
```

it throws me an error indicating cloudpickle is not installed, however, the earlier java -jar command passed smoothly confirming that the cloudpickle dependency is indeed there at
`~/.m2/repository/org/python/jython-standalone/2.7.3/Lib/site_packages`.

What am I missing? How do you think I could solve this?

Thanks and regards,

Paddy

**Comment by Stewori** [comment]
Perhaps, cloudpickle uses C-extensions which Jython does not support (are there .dll, .pyd, .so or .dylib files in the library folder?). C-extensions would appear to be "invisible" modules. Also, I recommend checking sys.path and to verify that the library is actually present at some location on that path. Also2, please post the exact error message (c/p console output) when reporting issues (not only for Jython, but in general).

Does it make a difference if you run in Jython (e.g. in the console) `import cloudpickle`? I.e. without using PythonInterpreter. In other words, is the issue specific to the class PythonInterpreter or is it a general Jython issue.

**Comment by tvpadmanabhan** [comment]
It was a syntax error that caused the problem, I had to surround the cloudpickle call in interpreter.exec call which I had missed.
