### ISSUE TITLE
Is it possible to change python version used by Jython 2.7.3?

### ISSUE THREAD

**Issue by tvpadmanabhan** [jython/jython#319]
Hi all,
     Can the Python version used by Jython be changed to 3.11? I realize that this can cause problems due to version mismatch but I am getting a lot of errors in trying to use 2.7.18 everywhere. I also searched how to set the Python version used by Jython but couldn't find anything. I don't have a stack trace to show for this requirement.

Thanks and regards,
Paddy

**Comment by yogi1967** [comment]
Jython 3 simply does not exist. There is no Python (version) within Jython. Jython *is* 'the Python'. I believe that a Jython 3 version is a very long way away...

**Comment by jeff5** [comment]
> Hi all, Can the Python version used by Jython be changed to 3.11?

Yes. Jython doesn't "use" Python, it implements it. All we need do is write (quite a lot of) Jython over again, and this is happening, but not quickly.
