### ISSUE TITLE
What java version that works to run jython

### ISSUE THREAD

**Issue by juniartisu** [jython/jython#328]
Hi,
Does anyone know the answer to below questions?
Will jython2.1 runs on Java17?
Will jython2.7.2 run on Java17?
Thank you.

**Comment by robertpatrick** [comment]
@juniartisu Jython 2.1 is very old so it seems unlikely that it will run on Java 17.

Jython 2.7.2 works with Java 8 or newer so it should work on Java 17.  We are using 2.7.3 on Java 17 without issues (other than Jython bugs being addressed in 2.7.4)
