### ISSUE TITLE
Question: Timeline for full release of 2.7.4?

### ISSUE THREAD

**Issue by JonathanBerkeley** [jython/jython#341]
Hello, this isn't an issue but a question, I hope this is the correct channel for it.

Is there an approximate date/timeline for the full release of version 2.7.4?

**Comment by robertpatrick** [comment]
@jeff5 I have the same question...

**Comment by jeff5** [comment]
You're aware of the beta of course, but I've been a bit distracted from an rc1 by other projects. I hate to give dates, but if it's a straight run, I might make an rc1 this weekend and a release two weeks after.

I'm a bit behind with issues too, but I haven't (yet) seen any blockers to that.

**Comment by JonathanBerkeley** [comment]
Thanks for the reply, and for your work on this project. I'll close this as the question is answered.

**Comment by jeff5** [comment]
#342 looks like it might take a while to bottom out.

**Comment by JonathanBerkeley** [comment]
Closing as it has been released, thanks.
