### ISSUE TITLE
Maintain ucnhash.dat

### ISSUE THREAD

**Issue by Stewori** [jython/jython#344]
ucnhash.dat is required for the API in the [ucnhash module](https://apidia.net/java/Jython/2.7.3/?pck=org.python.modules&cls=.ucnhash), i.e. for looking up unicode characters by name. It should be updated for every new unicode release. Since Jython 2.7.4 release is approaching, it occurred to me that it has not been updated since 2017 for Unicode 9.0. Current release is Unicode 15.1.
I am preparing a PR for the update right now. The process is somewhat documented in `Misc/makeucnhashdat.py`, but I can write up more detailed instructions for the dev guide later.
One reason to open this issue is to have a proper associated issue number to reference in NEWS:
Updates to ucnhash.dat should be tracked somewhere and this can establish the convention to track them at least in NEWS with the canonical number of this issue, i.e. write a line
`    - [ GH-344 ] Updated ucnhash.dat to Unicode x.y.z`

**Comment by Stewori** [comment]
Update to Unicode 15.1 in PR #345.

**Comment by jeff5** [comment]
Does that close this?

If a change is minor enough (not saying this one is) I think opening a PR and citing that as the issue number in NEWS is ok. The numbers come from the same series.

It goes wrong where what seems minor to an inexperienced contributor actually turns out to require substantial discussion, which is then lost when we reject the PR to take a fresh approach. So it's right to err on the side of issue vs PR.

**Comment by Stewori** [comment]
Yes, I suppose it can be closed. There is no rule against using closed issue numbers in NEWS. One use case of keeping it open would be to discuss whether we might want to switch to using [getCharFromName](https://apidia.net/mvn/com.ibm.icu/icu4j/74.2/?pck=com.ibm.icu.lang&cls=.UCharacter#getCharFromName-java.lang.String-) from [ICU4J](https://apidia.net/mvn/com.ibm.icu/icu4j). However, the discussion can be cut short since its not worth changing this for Jython 2.7 series and the discussion probably comes too early for Jython 3 series. So, no point in keeping this open now. Do we somewhere have a release guide? Like steps to do before a release, e.g. update dependencies etc? If so, there should be an entry/reminder with instructions to update ucn hash.

**Comment by jeff5** [comment]
> Do we somewhere have a release guide?

[We do](https://jython-devguide.readthedocs.io/en/latest/release_jy.html), and I'm editing it right now, as I tend to with each release, and I have added a section for "Before you start".

This is the only bit of the dev guide that get's any attention. (The rest is something of a mess. I wish I hadn't made it by forking the CPython one now, but that's another story.)

**Comment by Stewori** [comment]
I wrote up detailed instructions. These are kind of easy to figure out, but when making a release, one has to take care of so much stuff. So, it might be helpful if instructions are really prepared such that no additional brainwork is required. If you do not want to pollute https://jython-devguide.readthedocs.io/en/latest/release_jy.html with such details, we may add them to a leading comment in make_ucnhash.py, where the release_jy.html already points. Or just add a link to this very post.

1) Get http://www.ibiblio.org/pub/Linux/devel/lang/c/mph-1.2.tar.gz
and compile it (usually) using `make` (you need a C compiler and a properly configured "make" command on the path).


2) Get `UnicodeData.txt` for current version:
E.g. for 15.1.0 it is:
https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt
(browse the parent directory https://www.unicode.org/Public to see what the latest version is)


3) From the folder `~/Misc`, run something like (adjust args to proper paths):

`python make_ucnhashdat.py UnicodeData.txt mph.exe`

`ucnhash.dat` is created in the working dir.


4) Move the created `ucnhash.dat` to `~/src/org/python/modules`, replacing the existing one.


5) Make an entry in NEWS as follows:
```
    - [ GH-344 ] Updated ucnhash.dat to Unicode x.y.z
```
Note that the filename "ucnhash.dat" does not reveal which unicode version is currently hashed.
Therefore, it is crucial to track that info, which we do in NEWS.
In addition, you may add a comment to `make_ucnhash.py` along the lines
```
    # Called 2017 with UnicodeData.txt for Unicode 9.0
    # Called 2024 with https://www.unicode.org/Public/15.1.0/ucd/UnicodeData.txt
```
but that is probably not the ideal place for this info. It was just a crutch to track this info until a better solution is established.
