### ISSUE TITLE
Nested function behavior produces unexpected output

### ISSUE THREAD

**Issue by mouchen626** [jython/jython#365]
I encountered an unexpected behavior when running the code. The code execution results did not match my expectations.

```python
def f(x):
    def g():
        print([x for x in range(10)])
        def h():
            print(x)
        return h
    print(x)
    return g
f(1)()()
```

**expected output:**
1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
1

**Actual Behavior:**
1
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
9

**Environment:**
Jython 2.7.4 (tags/v2.7.4:3f256f4a7, Aug 18 2024, 10:30:53)
Ubuntu

**Comment by yogi1967** [comment]
Local variable x is overriding the passed parameter x. 

Try [y for y ....
