### ISSUE TITLE
Update Darwin jffi library dependency

### ISSUE THREAD

**Issue by predi** [jython/jython#49]
Hi,

you need to update your Darwin jffi library dependency to at least version 1.2.23 as noted [here](https://github.com/jnr/jffi/issues/74). Otherwise users will not be able to notarize your releases for usage on latest MAC OS X operating systems.

jython-standalone-2.7.2.jar release is affected by this issue and fails notarization unless you manually replace the `libjffi-1.2.jnilib` file supplied within the JAR (not sure if safe to do).

**Comment by sreilly** [comment]
Seconded. Including the updated libjffi-1.2.jnilib is necessary for anyone who needs to notarize their apps, including for the mac app store.
