### ISSUE TITLE
Maven provides invalid link to License

### ISSUE THREAD

**Issue by JRSofty** [jython/jython#51]
During the analysis to see if the Jython project is solution for our commercial project, I attempted to identify the license under which the license is released. The [Maven repository](https://mvnrepository.com/artifact/org.python/jython-standalone/2.7.2) says that it is the "Jython Software License". As this is not a standard license (i.e.BSD, Apache Public License, GPL etc.) it requires me to review it before I can make a recommendation. Yet the link provided by Maven https://www.jython.org/Project/license.html returns a 404. Either the maven project needs updated to point to correct location, or the license needs uploaded to the correct location at the jython website.

I was able to find the license (Python Software License v2) link from the front page of the website.

**Comment by jeff5** [comment]
Should be fixed with #148 .
