### ISSUE TITLE
java: module not found: org.objectweb.asm.util

### ISSUE THREAD

**Issue by ghostidentity** [jython/jython#54]
Hi guys,

I have a project that implements modular design on Java 11. I have added jython as dependency but when I run the application, it says it is unable to find the module.  

On the screenshot attached (left side), the package org.objectweb.asm is visible but unsure why its happening.

I'd like to ask if there is workaround for this ?

Jython Version: 2.7.2
OS: Ubuntu 18
JDK version: 11

![Screenshot from 2020-08-07 22-46-34](https://user-images.githubusercontent.com/4637625/89657872-5f47f480-d900-11ea-9ac7-0c01d0b1e3ae.png)

Thanks,
Mark

**Comment by jeff5** [comment]
Our bundling of dependencies into über-JARs is ignorant about modular Java. See also https://bugs.jython.org/issue2924.

It's not there by intention, and our JARs are not modular, so I think we should be filtering these out. Consider using jython-slim as a dependency.

**Comment by jeff5** [comment]
This problem afflicts both the -standalone and plain JAR, but not the -slim one (or -dev). Question of filtering in the build, no doubt.

Seems like only the `asm` JARs are a problem.

**Comment by jeff5** [comment]
This seems at first to be related to the spurious `module-info` files, although I'm not really sure. If the JVM interprets them as indicators of a modular project, it could well be ... and it's wrong anyway.
