### ISSUE TITLE
Jython does not find the OJDBC driver when run from the command line

### ISSUE THREAD

**Issue by halloleo** [jython/jython#63]
I have a Jython script which  via the `java.sql` packages accesses an Oracle database. For this to work it needs the `ojdbc6.jar`. 

When I run the script from the command line via

```
java -jar lib/jython.jar my-script.py
```

the script starts up properly, but on the first SQL call it errors out with "*java.sql.SQLException: No suitable driver found*" indicating that it cannot find `ojdbc6.jar`.

How can I tell **with an option on the command line** where the script can find the `ojdbc6.jar`? 

#### Why the bold phrase "with an option on the command line"?

Separately I have set up the script inside an Eclipse Java project where I have added `ojdbc6.jar` (and of course `jython.jar`) as libraries. When I use a little wrapper Java class which instantiates a `PythonInterpreter` and calls the script via `PythonInterpreter.execfile` everything works fine: 
The script executes the SQL statements and gets the data from the Oracle database as expected. So clearly the Java project tells the script correctly where `ojdbc6.jar` is. But how can I do the same on the command line?

**Comment by jeff5** [comment]
The jython *command* provides options for specifying a class path. (`java -jar` doesn't.)

**Comment by halloleo** [comment]
Thanks @jeff5 ! Good to know. :-)
