### ISSUE TITLE
Jython calls a python script containing a dll file to report an error

### ISSUE THREAD

**Issue by ltyeamin** [jython/jython#65]
Problem Description:
I call my Python script through JPython. The Python script contains dll files. If you run it directly with the native Python interpreter, there is no problem, but it will report an exception with JPython.
Normal run result
------------------------------------------------------
D:\py>python test.py
请按任意键继续. . .
300
请按任意键继续. . .

-----------------------------------------------------------------------------------------------------------------------------------------
1. Jython calls a python script containing a dll file to report an error
from ctypes import * 
import os

os.system("pause")
dll = cdll.LoadLibrary('D:\\py\\testDll.dll')
dll = CDLL('D:\\py\\testDll.dll')
print(dll.add(100,200))
os.system("pause")

2. My Java code (JPython)
public static void main(String[] args) {
		PythonInterpreter interpreter = new PythonInterpreter();
		interpreter.execfile("D:\\py\\test.py");
		PyFunction pyFunction = interpreter.get("add", PyFunction.class);
		int a =19995;
		int b =10;
		PyObject pyObj = pyFunction.__call__(new PyInteger(a),new PyInteger(b));
		System.out.println(pyObj);
}
3. run result
``
Exception in thread "MainThread" Traceback (most recent call last):
  File "D:\py\test.py", line 7, in <module>
    print(dll1.add(100,200))
NotImplementedError: variadic functions not supported yet;  specify a parameter list ``
4. Relevant documents can be sent to your mailbox as attachments. We look forward to your reply, thank you

**Comment by Stewori** [comment]
ctypes support in Jython is limited. See my answers [here](https://github.com/jython/jython/issues/30#issuecomment-629661923) and [here](https://github.com/jython/jython/issues/29#issuecomment-629660742). That said, I would recommend to mention the Jython version when filing a bug report.
