### ISSUE TITLE
Can it use on android?

### ISSUE THREAD

**Issue by huhuang03** [jython/jython#66]
Like the title, I use in android. And an error throw when I build the apk.
```
More than one file was found with OS independent path 'META-INF/INDEX.LIST'.
```

**Comment by Stewori** [comment]
> Can it use on android?

In short: No.
In long: See my answers [here](https://github.com/jython/frozen-mirror/issues/42#issuecomment-233181994), [here](https://github.com/jython/frozen-mirror/issues/172#issuecomment-598730733) and [here](https://github.com/jython/frozen-mirror/issues/169#issuecomment-588345141) and the surrounding posts for context.

**Comment by shalva97** [comment]
Hi, any updates on here? all the links you posted return 404

**Comment by Stewori** [comment]
Seems like the entire issue section of the frozen mirror is gone, so the links cannot be restored. However, I also explained the issue in https://sourceforge.net/p/jython/mailman/jython-users/thread/1896240569.1567129544177.eu.faircode.email%40localhost/#msg36751902.
There is this question on StackOverflow https://stackoverflow.com/questions/11120130/programming-android-apps-in-jython, however the answers miss the runtime issue. I pointed this out in a comment on the question. However my comment is kind of invisible at the bottom. (Maybe you could vote it up...?)

**Comment by Stewori** [comment]
This is almost certainly a "won't fix" for Jython 2. The work required is so significant that it would target Jython 3 if done at all.

**Comment by jeff5** [comment]
Sorry, I think I broke those links by disabling issues on the frozen mirror (to prevent posting new issues).

It's an attractive idea for Jython 3. I think we need two features:

1. process Java byte code generated by Jython to Dalvik (in dev).
2. compile user Python to CPython byte code (dev and run-time).

An MVP has just the second one. Android contains the `invokedynamic` apparatus we use from ISTR version 9. I haven't tested the idea, nor am I limiting my feature use to conform.

**Comment by Stewori** [comment]
Point 1. should "merely" be a question of the right gradle magic. I suggest to draw inspiration from the [libgdx](https://github.com/libgdx/libgdx) toolchain which does multiplatform exceptionally well. (processing Jython with robovm for ios probably will remain a distant dream though...).
