### ISSUE TITLE
Eclipse statup: WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by JohnVorwald** [jython/jython#68]
I have Ubuntu running in WSL, with eclipse installed. The eclipse version is:

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2020-09 (4.17.0)

When starting eclipse, the following message is generated

(WASS_37) john@LAPTOP-CBKOSEPA:~/PycharmProjects/WASS$ eclipse
[2] 334
(WASS_37) john@LAPTOP-CBKOSEPA:~/PycharmProjects/WASS$ org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.
SWT SessionManagerDBus: Failed to connect to org.gnome.SessionManager: Error spawning command line “dbus-launch --autolaunch=38ee76100394572dfd0f28405f54be78 --binary-syntax --close-stderr”: Child process exited with code 1
SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Error spawning command line “dbus-launch --autolaunch=38ee76100394572dfd0f28405f54be78 --binary-syntax --close-stderr”: Child process exited with code 1
org.eclipse.m2e.logback.configuration: Logback config file: /home/john/eclipse-workspace/.metadata/.plugins/org.eclipse.m2e.logback.configuration/logback.1.16.0.20200318-1040.xml
org.eclipse.m2e.logback.configuration: Initializing logback
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PyJavaType (file:/home/john/installation/eclipse/eclipse/../../../.p2/pool/plugins/org.python.pydev.jython_8.0.0.202009061309/jython.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.python.core.PyJavaType
WARNING: Use --illegal-access=warn to enable warnings of further illesgal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Here's contents of the file logback.1.16.0.20200318-1040.xml

<configuration scan="true">
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
      <pattern>%date [%thread] %-5level %logger{35} - %msg%n</pattern>
    </encoder>
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
      <level>OFF</level> 
    </filter>
  </appender>

  <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
    <File>${org.eclipse.m2e.log.dir}/0.log</File>
    <rollingPolicy class="ch.qos.logback.core.rolling.FixedWindowRollingPolicy">
      <FileNamePattern>${org.eclipse.m2e.log.dir}/%i.log</FileNamePattern>
      <MinIndex>1</MinIndex>
      <MaxIndex>10</MaxIndex>
    </rollingPolicy>
    <triggeringPolicy class="ch.qos.logback.core.rolling.SizeBasedTriggeringPolicy">
      <MaxFileSize>100MB</MaxFileSize>
    </triggeringPolicy>
    <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
      <pattern>%date [%thread] %-5level %logger{35} - %msg%n</pattern>
    </encoder>
  </appender>

  <appender name="EclipseLog" class="org.eclipse.m2e.logback.appender.EclipseLogAppender">
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
      <level>WARN</level>
    </filter>
  </appender>

  <appender name="MavenConsoleLog" class="org.eclipse.m2e.logback.appender.MavenConsoleAppender">
  </appender>
        
  <root level="INFO">
    <appender-ref ref="FILE" />
    <appender-ref ref="STDOUT" />
    <appender-ref ref="EclipseLog" />
    <appender-ref ref="MavenConsoleLog" />
  </root>

  <logger name="com.ning.http.client" level="INFO" />
</configuration>

Attached is the log file from folder

\home\john\eclipse-workspace\.metadata\.plugins\org.eclipse.m2e.logback.configuration

[0.log](https://github.com/jython/jython/files/5358961/0.log)

**Comment by JohnVorwald** [comment]
[.log](https://github.com/jython/jython/files/5358975/default.log)
Here is the error log

**Comment by jeff5** [comment]
It does it much less in 2.7.2, and only where unavoidable.
