### ISSUE TITLE
-m arg broken: AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by selfisekai** [jython/jython#71]
```
 laura@iino  ~/haruhi-dl   master  ~/jython/bin/jython -m haruhi_dl           
Traceback (most recent call last):
  File "/home/laura/jython/Lib/runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/laura/jython/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "__pyclasspath__/haruhi_dl/__main__.py", line 19, in <module>
  File "__pyclasspath__/haruhi_dl/__init__.py", line 474, in main
  File "__pyclasspath__/haruhi_dl/__init__.py", line 474, in main
  File "__pyclasspath__/haruhi_dl/__init__.py", line 456, in _real_main
  File "/home/laura/jython/Lib/optparse.py", line 1582, in error
    self.print_usage(sys.stderr)
  File "/home/laura/jython/Lib/optparse.py", line 1602, in print_usage
    print >>file, self.get_usage()
  File "/home/laura/jython/Lib/optparse.py", line 1587, in get_usage
    return self.formatter.format_usage(
  File "/home/laura/jython/Lib/optparse.py", line 1565, in expand_prog_name
    return s.replace("%prog", self.get_prog_name())
  File "/home/laura/jython/Lib/optparse.py", line 1560, in get_prog_name
    return os.path.basename(sys.argv[0])
  File "/home/laura/jython/Lib/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
```

Analogous CPython 2.7 calls work well. This works as well with Jython:
```
 laura@iino  ~/haruhi-dl   master  ~/jython/bin/jython haruhi_dl/__main__.py 
Usage: __main__.py [OPTIONS] URL [URL...]

__main__.py: error: You must provide at least one URL.
Type haruhi-dl --help to see a list of all options.
```

Source code of the program if you need it: https://git.sakamoto.pl/laudom/haruhi-dl/-/tree/18f1134188b55a683cd44a90ee260bf8ff79ee8f

**Comment by dirkf** [comment]
Seems to be a regression between 2.7.1 and 2.7.2 where `sys.argv[0]` is `None` when running:
```
jython -m module.py --arg
```
The failure occurs when formatting the usage string in `optparse.py`, trying to include the `os.path.basename()` of the null program/script name.

According to the documentation of `sys.argv`, the value of `sys.argv[0]` must be a string:
>... argv[0] is the script name ... If no script name was passed to the Python interpreter, argv[0] is the empty string.

**Comment by jeff5** [comment]
@dirkf : helpful analysis, thanks.

> Seems to be a regression between 2.7.1 and 2.7.2 where `sys.argv[0]` is `None` when running:
> 

Yeah ok, I refactored `org.python.util.jython` quite a bit. It fixed some things (like `-i`) but obviously this slipped off.

> ```
> jython -m module.py --arg
> ```
This command line is wrong (should have no ".py") but it produces an interestingly weird behaviour, as Jython goes looking for package `module` and a module `py`.

I have a script `args.py`:
```
import sys

print "sys.argv = ", sys.argv
print "__name__ = ", __name__
print "__file__ = ", __file__
```
It demonstrates the bug thus:
```
PS Jython-2> dist\bin\jython -m args
sys.argv =  [None]
__name__ =  __main__
__file__ =  None
PS Jython-2> python -m args
sys.argv =  ['...\\Jython-2\\args.py']
__name__ =  __main__
__file__ =  ...\Jython-2\args.py
```
That's quite surprising, as this script dates from when I did the refactoring, and I'd have said I used it then to check my work.

The command with the spurious ".py" confuses everyone:
```
PS Jython-2> dist\bin\jython -m args.py
sys.argv =  ['-m']
__name__ =  args
__file__ =  __pyclasspath__/args.py
...\Jython-2\dist\bin\jython.exe: No module named args.py
PS Jython-2> python -m args.py
sys.argv =  ['-c']
__name__ =  args
__file__ =  args.py
C:\Python\2.7.18\python.exe: No module named args.py
```
I wouldn't call either of those right.

**Comment by dirkf** [comment]
`module.py` was a typo.

The actual test that caused this error for me (in the upstream of OP's fork):
```py
    def test_module_exec(self):
        if sys.version_info >= (2, 7):  # Python 2.6 doesn't support package execution
            subprocess.check_call([sys.executable, '-m', 'youtube_dl', '--version'], cwd=rootDir, stdout=_DEV_NULL)
```
And the BT:
```
test_module_exec (test.test_execution.TestExecution) ... Traceback (most recent call last):
  File "/home/runner/jython/Lib/runpy.py", line 161, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/runner/jython/Lib/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "__pyclasspath__/youtube_dl/__main__.py", line 19, in <module>
  File "__pyclasspath__/youtube_dl/__init__$py.class", line 475, in main
  File "__pyclasspath__/youtube_dl/__init__$py.class", line 475, in main
  File "__pyclasspath__/youtube_dl/__init__$py.class", line 58, in _real_main
  File "__pyclasspath__/youtube_dl/options$py.class", line 892, in parseOpts
  File "/home/runner/jython/Lib/optparse.py", line 1399, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/home/runner/jython/Lib/optparse.py", line 1399, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/home/runner/jython/Lib/optparse.py", line 1439, in _process_args
    self._process_long_opt(rargs, values)
  File "/home/runner/jython/Lib/optparse.py", line 1514, in _process_long_opt
    option.process(opt, value, values, self)
  File "/home/runner/jython/Lib/optparse.py", line 787, in process
    return self.take_action(
  File "/home/runner/jython/Lib/optparse.py", line 813, in take_action
    parser.print_version()
  File "/home/runner/jython/Lib/optparse.py", line 1619, in print_version
    print >>file, self.get_version()
  File "/home/runner/jython/Lib/optparse.py", line 1606, in get_version
    return self.expand_prog_name(self.version)
  File "/home/runner/jython/Lib/optparse.py", line 1565, in expand_prog_name
    return s.replace("%prog", self.get_prog_name())
  File "/home/runner/jython/Lib/optparse.py", line 1560, in get_prog_name
    return os.path.basename(sys.argv[0])
  File "/home/runner/jython/Lib/posixpath.py", line 121, in basename
    i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'
ERROR
```

If the comment [here](https://github.com/jython/jython/blob/d0467e78aa0ef5020f81d6d13ba7dca9f547fc5f/src/org/python/util/jython.java#L564) is right, something is going wrong later in `org.python.util.jython`.

In the same test run, we also get this error with accompanying instructions for an automatically generated test module:
```
java.lang.RuntimeException: Module or method too large
```
While I understand the reason for the error, will there be an internal Jython work-around, or should I investigate making the test generate a module that doesn't trigger the error?

**Comment by jeff5** [comment]
> `module.py` was a typo.

Understood. The symptoms evoked differ only because import is looking for a package and module. 

> In the same test run, we also get this error with accompanying instructions for an automatically generated test module:
> 
> ```
> java.lang.RuntimeException: Module or method too large
> ```
> 
> While I understand the reason for the error, will there be an internal Jython work-around, or should I investigate making the generate a module that doesn't trigger the error?

That's a different problem. Have you found the [work-around Jython offers](https://github.com/jython/jython/blob/d0467e78aa0ef5020f81d6d13ba7dca9f547fc5f/NEWS#L306-L309)? This requires you to have a CPython 2.7 around. If this is source you are generating, it is better to reduce the size.

**Comment by dirkf** [comment]
Yes, a bit tricky as it's a module (360kB) that comprises a list of small classes whose dependencies I'd rather not have to analyse beyond what's already done. Each class stands for an actual class used in the application and we don't have any problem with the modules containing those, including some that are up to 140kB. There are classes with >20k characters in a line but each class is much smaller than the class it fronts.

The issue occurs in a VM specifically run up to test the app with Jython, so CPython isn't really appropriate even if available.

**Comment by jeff5** [comment]
I added this note when to #168, but it belonged here ... 

The problem seems to come from `runpy.py` and `pkgutil` which should set `sys.argv[0]`. (Also `__file__`, which is `None` too.)

However,  the root cause of the error is possibly that we are not reproducing this from CPython
[main.c](https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Modules/main.c#L561-L576).  The arcane trickery with `argv` manipulates what `PySys_SetArgv` sees, which by side-effect also updates `sys.path`, and indirectly what `runpy` does to `argv[0]`.

Not really a model of transparent programming, this bit.
