### ISSUE TITLE
Version 2.5.1/2.5.2 build error:Target "jar-standalone" does not exist in the project "jython"

### ISSUE THREAD

**Issue by jimjiyn** [jython/jython#73]
When I builded version 2.5.1(or 2.5.2) of  jython-standalone，it returned:

`[root@localhost frozen-mirror-2.5.2]# ant jar-standalone
Buildfile: /home/jython-standalone/frozen-mirror-2.5.2/build.xml

BUILD FAILED
Target "jar-standalone" does not exist in the project "jython".
`
I saw there is no target jar-standalone in build.xml. But  I found these versions of jython-standalone in Maven Central Repository:https://search.maven.org/artifact/org.python/jython-standalone
How can I build these versions using source code ?

**Comment by jeff5** [comment]
`ant -p` tells you what targets exist. Build for supported versions is described [here](https://jython-devguide.readthedocs.io/en/latest/release_jy.html#ant-build-for-release). If this doesn't work for 2.5.x, you would have to read `build.xml` to figure out why.
