### ISSUE TITLE
Broken AST adapter

### ISSUE THREAD

**Issue by Tobias-Kohn** [jython/jython#77]
[One of the AST-Adapters](https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/antlr/adapter/AstAdapters.java#L63) is broken.  The method `py2int` should accept a `PyInteger` or `PyLong`, not a Java `Integer`:
```java
    public static Integer py2int(Object o) {
        if (o == null || o instanceof Integer) {
            return (Integer)o;
        }
        return null;
    }
```
*Reproduction of the error:*  Create an instance of the `org.python.antlr.ast.ImportFrom` class and try to set the `level` attribute.
```java
        ImportFrom i = new ImportFrom();
        i.setLevel( Py.newInteger(123) );
        System.out.println( i.getLevel() );   // <- NullPointerException here!
```
*Fix:*  The adapter should probably read:
```java
    public static Integer py2int(Object o) {
        if (o instanceof PyInteger) {
            return ((PyInteger)o).getValue();
        }
        if (o == null || o instanceof Integer) {
            return (Integer)o;
        }
        return null;
    }
```

**Comment by jeff5** [comment]
@Tobias-Kohn : The pattern in other methods is to test first for the expected thing, then _sometimes_ also for kinds of `PyObject`, so I'll do this the other way around, but basically yes. (And in fact, I think you know more about this bit of Jython than I do.)

I wonder if others that don't accept a `PyObject` need the same treatment, `py2bool` perhaps, or we should wait another 13 years for someone to need it? ;)

**Comment by jeff5** [comment]
Alternative to reproduce from Python:
```
>>> from ast import *
>>> dump(ImportFrom('math', [alias('sin', None)], 0))
```
The stack dump comes from accessing the level value in `dump`, not from setting it.

I thought incorrectly that I would be able to reproduce it with:
```
>>> dump(parse("from math import sin"))
"Module(body=[ImportFrom(module='math', names=[alias(name='sin', asname=None)], level=0)])"
```
but as shown, the tree can be dumped.

This answers my question whether `py2bool` has the same bug:
```
>>> dump(Print(dest=None, values=[Num(n=42)], nl=True))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\dist\Lib\ast.py", line 110, in dump
    return _format(node)
  File "...\dist\Lib\ast.py", line 94, in _format
    fields = [(a, _format(b)) for a, b in iter_fields(node)]
  File "...\dist\Lib\ast.py", line 168, in iter_fields
    yield field, getattr(node, field)
  File "...\dist\Lib\ast.py", line 168, in iter_fields
    yield field, getattr(node, field)
java.lang.NullPointerException
        at org.python.antlr.ast.Print.getNl(Print.java:58)
...
```
