### ISSUE TITLE
Ant Build Task Failed

### ISSUE THREAD

**Issue by tbpassin** [jython/jython#85]
In trying to build Jython from the current master branch, ant stopped with this error:

java.lang.TypeNotPresentException: Type org/python/core/PyObject not present

However, PyObject.class is in fact present in the build subtree, so apparently ant was able to compile it.

I'm asking for some guidance about how to proceed.

**Comment by Stewori** [comment]
Would you please share the exact command you used for building?

**Comment by tbpassin** [comment]
"ant".  It gets partway through compiling, then emits that message and quits.

I have repeated it a few times after _ant clean_ with the same results.

The distro is one I cloned today from the jython GitHub site.  I also went back to the 2.72 release revision, and got the same result.  It's always complaining about not finding PyObject:

`java.lang.TypeNotPresentException: Type org/python/core/PyObject not present`

Oh, yes, I'm on Windows 10, jdk1.8.0_231.  The Ant install I just did today:

`Apache Ant(TM) version 1.10.9 compiled on September 27 2020`

I've got to admit it's strange, because after all the 2.72 release **was** built for release (I use it), and presumably built with ant.  Though the repo might still have been on Hg back then, and I see that the build.xml file would still like to use Mercurial if it can be found.

I noticed in the build.xml file a line that wanted to make the compile java 7 compatible.  I commented that out in case some java 8 feature had crept into the code somewhere, but got the same result - not a surprise.

**Comment by Stewori** [comment]
It appears that I cannot reproduce this issue on Linux Mint 18 with Java 8. Just running "ant" compiles Jython successfully based on a fresh clone from this repo.

``openjdk version "1.8.0_275"``
``Apache Ant(TM) version 1.9.6``

**Comment by tbpassin** [comment]
Maybe I will try that - I sometimes run a Mint VM.  The class files should work on Windows.  I will report on the results.

**Comment by tbpassin** [comment]
It might be worth while for me to install the same version of Ant as you have and try that on Windows.  Maybe Ant 1.10.x works a bit differently from 1.9.x...

**Comment by tbpassin** [comment]
I succeeded building on Linux Mint.  Mint had a package for Ant, so that's what I installed.  The Ant version:

`Apache Ant(TM) version 1.10.5 compiled on March 28 2019`

I haven't tested anything yet.  My main interest just now is recompiling PyServlet for the jakarta.servlet namespace instead of the old javax.servlet, and this compile was an essential start.

Still, it would be good for a Windows build to succeed.

**Comment by tbpassin** [comment]
On Windows, I tried using Ant 1.9.10 and this build succeeded.  So Ant 1.10.9 failed on Windows, while 1.9.10 worked.  I'll try 1.10.5 next, since that succeeded in Linux.

**Comment by tbpassin** [comment]
A build on Windows with Ant 1.10.5 succeeded.  This leaves us with the nasty problem of whether Ant 1.10.9 has a bug, or whether there is a bug in the build.xml file that wasn't a problem before.

**Comment by jeff5** [comment]
It works for me with:
```
PS git> java -version
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
PS git> ant -version
Apache Ant(TM) version 1.9.14 compiled on March 12 2019
```
and downloading the head revision from `https://github.com/jython/jython.git`. I'm on Windows 10 (and in posh), so really very like your setup.

I've never seen the like of that message. It sounds like it is the result of actually running Jython after it has been built, which would make it the jycompile stage. You don't say what stage of the build it occurs.

If it varies with Ant version, I would guess that it is something to do with the custom Ant task. But it's only a guess.

**Comment by tbpassin** [comment]
On my failures, it never got to the jycompile stage.  I am fairly sure it was in the "Expose" stage. 

It seems to me that if a class file - that I have seen has been built - can't be found, then the problem must be with a path somewhere, presumably a class path.  These paths are constructed either in the build file or by ant based on the build file.

I also noticed a lot of warnings during the build, but they scrolled by so fast I couldn't take them in.  Running the build with the earlier version of Ant, the one that succeeded, I didn't see all those warnings.  I suppose they weren't actual errors or the build would have stopped sooner.

**Comment by jeff5** [comment]
I get warnings about the grammar, but less than a screenful. The exposer is an Ant task too, so maybe that's the one that's failing with later versions of Ant.

**Comment by tbpassin** [comment]
I think that's right.

**Comment by cclauss** [comment]
https://travis-ci.org/github/jython/jython/pull_requests seems to be failing.

**Comment by jeff5** [comment]
Note to self (mostly): update ant so that we build 2.7.3 with a recent version.

**Comment by jeff5** [comment]
I updated to Ant version 1.10.12 locally, a good bit of housekeeping. But I can't reproduce this problem, so I'm closing it. It is also worth saying it builds fine with Ant on multiple build bots -- see any recent commit.
```
PS Jython-2> java -version
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
PS Jython-2> ant -version
Apache Ant(TM) version 1.10.12 compiled on October 13 2021
```
I would suspect something in the environment or maybe the path? But apart from having set `JAVA_HOME` (and un-setting didn't seem to affect matters) I can't see what would would make mine different from @tbpassin's.
