### ISSUE TITLE
PythonInterpreter tcp socket connection error 

### ISSUE THREAD

**Issue by orshih6** [jython/jython#86]
im using  pyzk lib. but it is error connection timeout. tcp connection not working

**Comment by jceyca** [comment]
Hello Orshih6, do you fix the problem? i have the same problem, i read that the problem is with sockets creation, but i dont found a fix for this.

**Comment by orshih6** [comment]
Hello jceyca, no i don't. I changed technology.

**Comment by jeff5** [comment]
We would need an example that pinned the blame on Jython to investigate.
