### ISSUE TITLE
Jython upgrade ?

### ISSUE THREAD

**Issue by hv321** [jython/jython#90]
Hello,

Can you inform me if and when there are plans to synchronize Jython to the latest Python development? We are using Jython as scripting language for our in-house developed test automation framework but starting to get obsolescence issues with current Jython 2.7.2.

Kind regards,
H

**Comment by aisk** [comment]
Please take a look at main branch.

**Comment by jeff5** [comment]
Or shorter: https://www.jython.org/jython-3-roadmap

**Comment by hv321** [comment]
Thanks for that, I already found that information but was hoping for some insides, planning wise. Reading this and looking at the repo I conclude that a new release is not at all imminent. Is that a correct conclusion?

**Comment by jeff5** [comment]
Definitely not imminent. I'm working on it off the main repo because of the possibility of dead ends.

**Comment by hv321** [comment]
thank you for the update
