### ISSUE TITLE
Permissions problems with compiled source files ($py.class)

### ISSUE THREAD

**Issue by joeshannon** [jython/jython#93]
Jython 2.7.2 includes a fix for https://bugs.jython.org/issue2044 which explicitly sets the permissions on the compiled class files to  u=rw/600 (unix permissions) - this  is set in `org.python.core.util.FileUtil.makePrivateRW`.

Our application is deployed to a network file share where it is run by multiple users (some with write access). With Jython 2.7.2 we are getting failures:
```
IOError: [Errno 2] File not found - /some/path/my_module$py.class (Permission denied)

	at org.python.core.Py.fromIOException(Py.java:214)
	at org.python.core.Py.IOError(Py.java:183)
	at org.python.core.imp.makeStream(imp.java:218)
	at org.python.core.imp.loadFromSource(imp.java:929)
	at org.python.core.imp.find_module(imp.java:769)
...
```
This happens when the second user runs the application, after the class file has been written with the restricted permissions.

Are there any known workarounds for this? We have been setting `dont_write_bytecode = true` on `PySystemState` but this is potentially not ideal.

A possible fix for this would be to enhance the `haveCompiled` flag in `impl.loadFromSource` to check that the file is readable before attempting to open it, if it is not then can proceed to call `createFromSource`. Does this sound reasonable?

**Comment by jeff5** [comment]
Thanks for diagnosing and reporting this,

The command line option `-B` will also suppress writing byte code.

Jython is mimicking CPython (2.x) behaviour in writing its compiled code adjacent to the source. The change that gives the files owner-only access responds to a security advisory about allowing users to replace files others then execute with their own rights. 

I'll admit I hadn't thought about the case where you share source. It would be better if the compiled code went to a per-user cache in the way we (now) have for indexes of JARs. (This is for the same reason.)

A look at the code suggests that if the shared directory were not writable, the write would fail harmlessly (with a log message at worst). There is clearly a performance penalty in re-compiling every time. If it were significant, perhaps you could allow a user privileged to write, to compile the files for everyone else (and fix the permissions).

**Comment by Stewori** [comment]
Did you consider to compile the python sources to Java bytecode ahead of time?

```
java -cp whatever org.python.util.jython -c "import compileall; compileall.compile_dir('some_path')"
```
I am not sure how this would set the permissions of the created files, but you should be able to edit the permissions afterwards to your liking before deployment.

**Comment by joeshannon** [comment]
Thanks for the responses. These workarounds may be useful for some situations, but will not solve our problem entirely:

- Some of the python sources involved are "user" scripts, stored in a shared directory. These cannot be precompiled as they may not exist when the application is deployed
- The application makes use of the PyDev editor in Eclipse. PyDev spawns several external Jython processes (e.g. a code completion server). As this process management is internal to PyDev we can't pass in the `-B` argument. PyDev does support environemnt varialbles however, and CPython has the `PYTHONDONTWRITEBYTECODE` environment variable but unfortunately this is not supprted in Jython (it is referenced in a comment in the [jython](https://github.com/jython/jython/blob/0a58cc26566d2b2334e80b2b3f2f42f6c738db2d/src/org/python/util/jython.java#L109) entrypoint class)

**Comment by joeshannon** [comment]
Would you be happy to accept pull requests for either/both of these enhancements?

1. Fall-back to using the source if the compiled bytecode is present but non readable (as far as I can tell this matches CPython behaviour)
2. Support the `PYTHONDONTWRITEBYTECODE` environment variable in the main jython app/class

**Comment by alexgobbo** [comment]
Controlling the rights of the .class files is desirable but the greatest problem is that when the .class file exists, and Jython fails reading it because of the rights, then it doesn’t try to re-compile the source (as it does when there is any error importing the .class file, other than permission denied), even if _dont_write_bytecode_ is set.

Independently how (and if) this issue will be fixed, my suggestion is also changing loadFromSource in org/python/core/imp.java, disregarding the exception thrown by makeStream when opening the .class file - and trying to compile the source in this case:
```
if (haveSource) {
    // Try to create the module from source or an existing compiled class.
    long pyTime = sourceFile.lastModified();
    if (haveCompiled) {
       // We have the compiled file and will use that if it is not out of date
       logger.log(Level.FINE, "# trying precompiled {0}", compiledFile.getPath());
       long classTime = compiledFile.lastModified();
       if (classTime >= pyTime) {
       // The compiled file does not appear out of date relative to the source.
       PyObject ret = null;
       try{
         ret = createFromPyClass(modName, makeStream(compiledFile), //
            true, // OK to fail here as we have the source
            displaySourceName, displayCompiledName, pyTime);
       } catch (Exception e) {
       }                  
```
Or else  _haveCompiled_ should be _true_ only if we have read permission on the .class file.
Or else Jython shouldn’t try to load compiled files if _dont_write_bytecode_ is set.
