### ISSUE TITLE
jython-standalone-2.7.2.jar appear by accident "ImportError: No module named XXX"

### ISSUE THREAD

**Issue by sunlei19900612** [jython/jython#94]
Java code call python code via jython-standalone-2.7.2.jar appear by accident "ImportError: No module named XXX". XXX is a package name. First I have set the correct sys.path. And there is __init__.py under each package. The following error appear by accident.
![image](https://user-images.githubusercontent.com/83343381/116397346-11419b00-a859-11eb-9074-f31f2ac6633d.png)

I read the source code of jython. Found bellow:
![image](https://user-images.githubusercontent.com/83343381/116397472-346c4a80-a859-11eb-9914-15c809f197f9.png)

The import_first method calls import_next method, and then calls find_module method. In th find_module method. Traverse all sys.path, splicing each path with module name, if the path after stitching is a existing directory. Then can find this module. If the path after stitching is a directory that does not exist. Then throws Py.ImportError of "No module named XXX".
Is this a bug or the way I am using is wrong?

Please, thanks everyone!

**Comment by zhouqunhua** [comment]
Need help.

**Comment by jeff5** [comment]
It is difficult to help without knowing more about what Python is being executed and the state of the import system.

If you raise the verbosity level (-v flag on the command line, or [Py.setLoggingLevel](https://www.javadoc.io/static/org.python/jython-standalone/2.7.2/org/python/core/PrePy.html#setLoggingLevel-java.util.logging.Level-)) it will tell you where it is looking. If you can't then work it out, we'd have more to go on.

The import mechanism is confusing, and may have long-standing problems. I wrote myself [some notes](https://inside-jython.readthedocs.io/en/latest/import.html) in which the examples may help you, but I think it needs re-working from the ground up (as CPython has).

**Comment by jeff5** [comment]
I guess that helped.
