### ISSUE TITLE
Jython urllib does not support HTTP/2 

### ISSUE THREAD

**Issue by thypon** [jython/jython#99]
At the current stage HTTP/2 requests are not supported at all and will fail when completing a request on a HTTP/2 enabled server. It seems like even pip is affected by this issue on Jython.

https://github.com/doyensec/inql/issues/37#issuecomment-861386519

**Comment by jeff5** [comment]
Our `urllib` is the same as the one distributed with CPython 2.7.18, except to fix the OS platform detection.

`socket` is entirely different, however.

**Comment by jeff5** [comment]
Is the issue about the failure to support SNI (the hostname match message in #97) or is it the compression aspect of HTTP/2?

`pypi` seems willing to deliver in HTTP/1.1, but insists on SNI.

**Comment by jeff5** [comment]
@thypon : looking at the context of the original post, I think your problem is with our handling of SNI, fixed in #97, so this is a duplicate. Would you agree?

**Comment by thypon** [comment]
I think so, yup. CPython does not support HTTP/2 either way.
